CHANGELOG, Doc/source/datamodel.rst, setup.py, spacepy/ae9ap9.py, spacepy/datamodel.py, spacepy/plot/utils.py, spacepy/toolbox/__init__.py, tests/test_datamodel.py, tests/test_toolbox.py
This is to simplify the process of #2
=> Updating the repository to the latest official version

CHANGELOG, developer/scripts/spacepy_win_anaconda.py, spacepy/poppy.py, spacepy/pycdf/__init__.py, tests/test_pycdf.py
Get the last commits from SF after making the repo read-only.
=> Final SF sync

developer/benchmarks/pycdf/entry_typing.py
This is a pycdf benchmark that's been sitting around for awhile (for something that's remarkably slow) and finally committing it.
=> benchmark: add pycdf entry typing

Doc/source/conf.py
Somehow I managed to screw up the fix for #35 so hopefully this fixes the fix...
=> Fix imgmath import check in sphinx conf

spacepy/lib.py
Minor update to lib.py to close #75.  Have a look.
=> lib.py: update to fix the SO to EXT_SUFFIX deprication, closes #75

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, code-of-conduct.md
Provides initial versions of templates for:
- Pull requests
- Issues
These are related to #40, but don't quite fulfill everything there.
Provides initial code of conduct based on contributor covenant, plus some preamble. (Closes #70 )
=> Workflow: Templates for PR, issue; Code of conduct

setup.py
This PR detects if pip is calling setup.py to get egg info, and if so, allows all the numpy distutils related code to fail relatively gracefully, downloading numpy before the spacepy install. It still seems to throw an error message trying to build the spacepy wheel, but successfully installs by calling setup.py. It's probably trying to build the wheel before finishing the install of everything else.
=> setup: fix pip when numpy not installed (Closes #45)

Doc/source/install_mac.rst
This is requested updates the the mac install docs. Not perfect but I verified these to work which is more important. 
Thoughts? Edits? I don't have a ton of time to edit so others feel free.
=> Mac install docs

tests/test_toolbox.py
Minor updates to test_toolbox.py for more test coverage. This uncovered  #184.
=>  test_toolbox.py: updated for more test coverage

tests/test_ae9ap9.py, tests/test_datamanager.py, tests/test_datamodel.py, tests/test_pybats.py, tests/test_pycdf.py, tests/test_toolbox.py
This is work toward #178. Cannot close yest but this and the other pulls fix all but omni.
=> Issue178, work on not closed yet, omni thoughts needed

Doc/source/index.rst, Doc/source/pythonic.rst
This has come up in the pyhelio discussions of "hey, what's Pythonic code" and I figure we can help provide an answer. There's some overlap with the tips document but this is an attempt to explain why (and then link out to the exhaustive lists of do-this-not-that.)
This can definitely be improved so I'm happy to iterate on the branch for awhile, or merge and improve later.
=> Short doc on pythonic code

spacepy/irbempy/irbempy.py
Docstring update explaining negative L values.
=> irbempy: Document negative L in Lm, Lstar (Closes #104)

spacepy/toolbox/__init__.py
This PR builds on #219 to do the unzip in a temporary directory so that if cleanup fails, it won't stay around forever. That change also fixes the case where the working directory isn't writeable.
PR also changes the handling of the zipfile to make sure it's the structure we expect (single file, no paths specified) so that it doesn't splat files in places they should go. We normally trust ViRBO but in case the URL winds up not actually going to their site, we don't want to blindly extract a zip that might replace `/etc/passwd`.
=> toolbox.update: do OMNI2 work in a temp directory, safer ZIP handling.

spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
This PR adds to the DELTA checks by comparing the shape of the DELTA to its parent variable.
=> pycdf.istp.VariableChecks: Check shape of DELTA variables.

CHANGELOG
This PR simply notes the improvements from #255 in the CHANGELOG.
=> CHANGELOG entry for EventClicker updates

CHANGELOG, spacepy/plot/__init__.py, spacepy/pybats/bats.py, spacepy/pybats/kyoto.py
Fixed an issue where Kp plots from pybats.kyoto where incorrect.  Underlying issue was creation of the time boundaries on bins; this has been rectified.  Added a small change to how legend labeling for these plots is done within spacepy.pybats.BatsLog and GeoIndexFile objects.
Closes #252
=> pybats.kyoto: Fix histogram-style Kp plots.

CHANGELOG, spacepy/pybats/bats.py
Closes #272 
Small fix to properly pass tolerance kwarg within tracing routines.
- [ x] New code has inline comments where necessary
- [ x] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [x ] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
=> pybats.bats: Fix tolerance passing in add_b_magsphere

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This was supposed to be something where I sped up attribute access (thus the name) but that turned out to be less important for the case I was working on, so this is just some general cleanup of things I found while working on that. Some typos (including one that introduced a bug), some more testing of things that I wasn't sure about, a little bit of refactoring.
=> pycdf minor cleanups

README.md
- The spacepy repository README did not have a DOI badge within the file.  A master DOI badge was added to the top of the file that will point to the latest release version.  
- This PR resolves #247
=> Added DOI Badge to README

CHANGELOG, spacepy/plot/__init__.py, spacepy/plot/utils.py, spacepy/pybats/__init__.py, spacepy/pybats/bats.py, tests/test_plot_utils.py, tests/test_pybats.py
This pull request adds a handful of new useful features:
- New function to plot.utils: add_arrows, which adds arrows to indicate the direction of a line (e.g., magnetic field).
- New pybats.bats.Bats2d method for adding stream traces to a plot: add_stream_scatter, which scatters streams randomly over a plot.
- add_arrow integrated into pybats.bats.Bats2d.add_b_magsphere and add_stream_scatter. Accessible via keyword arguments.
- a handful of small bug fixes to improve robustness.
=> New feature: randomly-seeded stream plotting and arrows to lines (conflicts resolved)

spacepy/pycdf/istp.py
* Fix a FutureWarning calling issubdtype with a non-generic type
=> pycdf.istp: fix deprecation (Closes #327)

Doc/source/dependencies.rst, Doc/source/toolbox.rst, spacepy/toolbox/__init__.py
This PR adds to the dependencies document a table of exactly what functionality depends on what soft dependencies. There's also some incidental cleanup of documentation linking for toolbox, and some updates in the main flow of the dependencies doc.
Note that some of the links (to pybats particular) aren't working. That's because those pybats docstrings aren't brought into a toctree, so they aren't built...that's an issue for another day.
=> Summarize dependencies and their functionality (Closes #8)

spacepy/pybats/__init__.py
Discussion in #298 mentioned that the writing could be slow. I managed to wring out a 25% speed increase; I doubt there's much more to be had without changing internal time representation. On read, I managed to cut the time in half.
I'm relying on the unit tests to make sure this is right--in particular, there's a possibility of having typoed the handling of some of the headers if they weren't tested.
=> Speed up pybats.ImfInput read/write

Doc/source/_templates/layout.html, Doc/source/capabilities.rst, Doc/source/conf.py, Doc/source/index.rst, Doc/source/publications.rst, Doc/source/toolbox.rst
Primarily this PR closes #56 but it also makes several other documentation changes:
- Rearranges the index page so the getting-started material stands out
- Adds a publication we were missing on the pub list (I'm sure there are many others)
- Adds our Zenodo ref to the citation information
- Changes the HTML template so the "homepage" link goes to spacepy.github.io instead of the github code repo and adds a "development" link to the repo.
=> Capability list and other documentation improvements

setup.py, spacepy/irbempy/irbempy.py, tests/test_irbempy.py
This PR adds support for the landi2lstar IRBEM routine to compute Lstar values. It allows for fast Lstar computation when the magnetic fields are compatible. It is added as a boolean flag to the `get_Lstar` function, which defaults as False for compatibility reasons.
Also, the subroutine call code in the _get_Lstar function has been corrected to call appropriate routines (make_Lstar, landi2Lstar, and their shell_splitting counterparts). The shell_splitting versions are called if more than one alpha angle is provided, or the provided angle is not 90 degrees.
This PR requires to rebuild the IRBEM library, as it adds wrappers to new subroutines.
=> irbempy: add support to the landi2lstar IRBEM routine to compute Lstar.

Doc/source/conf.py
Update to the address for numpy inersphinx
- [x ] Pull request has descriptive title
- [ x] Pull request gives overview of changes
- [ n/a] New code has inline comments where necessary
- [ n/a] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ n/a] New features and bug fixes should have unit tests
- [ x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Doc: source/conf.py. Closes #384, Update to the address for numpy inersphinx

spacepy/plot/utils.py
Docstring updates, the heading should read `Examples`
- [X ] Pull request has descriptive title
- [ X] Pull request gives overview of changes
- [ n/a] New code has inline comments where necessary
- [ n/a] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ n/a] New features and bug fixes should have unit tests
- [X ] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> plot/utils.py: update docstring Example->Examples

CHANGELOG, spacepy/datamodel.py, tests/test_datamodel.py
- [X ] Pull request has descriptive title
- [ X] Pull request gives overview of changes
- [ X] New code has inline comments where necessary
- [ X fixed] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [ X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ X fixed ] New features and bug fixes should have unit tests
- [ X ] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
This is related to #305, `createISTPattrs` needed else handler for datatype. Documentation was added and unittests, really regression tests as this is a "factory" function
=> createISTPattrs needed documentation and testing

Doc/source/irbempy.rst
This PR adds `find_footpoint` to `irbempy.rst` so it shows up in the docs. See #492.
=> irbem: expose find_footpoint in docs

Doc/source/publications.rst
Added Gieseler et al. 2020 to the "Publication List" (under "Papers using SpacePy" / "Peer-reviewed papers") (and added a missing `.` at the end of the entry for Jordanova et al. 2014).
**Note:** There are some umlauts (ö, ä, æ) in the author list of the added publication; I don't know if this could cause problems somewhere in the process.
Mentioned at [#532](https://github.com/spacepy/spacepy/issues/532)
=> Docs: publications: Add Gieseler et al 2020

Doc/source/release_notes.rst, spacepy/ae9ap9.py, tests/data/ephem_AE9test.dat, tests/test_ae9ap9.py
The output file format for orbit info changed and we needed to change also. 
- [n/a] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [n/a] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> ae9ap9 input file format updates

spacepy/toolbox/__init__.py
This PR reworks how `toolbox.update()` processes the omni 1 / Qin-Denton files to allow it to work on Raspberry Pi, specifically on my model 3B with 1GiB RAM on Python 3 (although 2 is also tested, FWIW). Closes #434.
There are three parts to the strategy:
- Keep data in bytes, instead of strings, as long as possible to save memory
- Delay some jump to numpy arrays until the data have been filtered
- Delete intermediate products aggressively, and delete the final product before moving on to the next.
On my main Linux box, `update()` runs at least as fast with these changes as before.
Because our data sources for omni are down, testing this is a little difficult. The downloaded Q-D files must already exist in `.spacepy/data` for the assembly. The call to `_crawl_yearly` in …
=> Fix toolbox.update on Raspberry Pi

spacepy/irbempy/__init__.py, tests/test_irbempy.py
This pull request improves the test coverage of the irbempy submodule, up to 88% from about 80%. Also, some minor bug fixes and code improvements along the way. Closes #307 and (slightly off-topic) #768.
The bulk of the improvements came from testing cases where the internal irbemlib call returned close to badval, and the further handling as np.nan. I also added some regression tests for untested edge cases and in some cases, complete functions (`find_Lm`). All the new tests are regression tests since I do not have a first principles understanding of the code.
What's still missing is some harder-to-hit edge cases and the hard-to-test header code.
Unfortunately, the edge cases in `find_LCDS` and `find_LCDS_K` mean those functions have to be run several times, causing`test_irbempy.py` to …
=> irbempy: Improve test coverage

Doc/source/release_notes.rst, spacepy/irbempy/__init__.py, tests/test_irbempy.py
Depends on #769.
This pull request closes #750. It fixes an issue with find_Bmirror where input pitch angles aside from the first are ignored completely, and handled as if there was only one.
Review will be required to verify the correctness of this. Initially, I imagined the fix would be to give each output a new 'pitch angle' dimension, however both 'loci' and 'Blocal' do not depend on pitch angle at all. 'Bmirr' is the only output field that was changed, and it is now in dimensions nTAI x nalpha. It is also unclear to me whether we'd want 'Bmirr' to always be 2-dimensional (even if alpha contains only one pitch angle), or if we'd want the number of dimensions to depend on whether there's more than one pitch angle.
=> irbempy: fix find_Bmirror ignoring pitch angles
