spacepy/spacepy

spacepy/toolbox/__init__.py
Testing the pull request workflow. There was a deprecated call in toolbox anyway. 
`matplotlib.mlab.prctile` -> `numpy.percentile`
Not really sure why we used the matplotlib version in the first place. Tests all pass with numpy.
=> toolbox: removed a call to the deprecated matplotlib prctile

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
We had some issues with accidentally reading NRV variables that had never been written to; basically this returned default CDF pad data (not desired). I got this to work more like RV variables with the exception of scalars, which I don't even know what should be the right behavior. I'm going to open an issue for that; in the meantime, this should be a substantial improvement.
=> pycdf: handle reading empty NRV variables

tests/test_lib.py
One of the big issues I'm having in the Windows port is memory access violations when loading libspacepy or irbem. We don't have any tests that just hit libspacepy; most of them pull in the full Python machinery, so keeping libspacepy stuff separate from irbem is a bit unpleasant. This PR gives a few tests that just push on the C library.
=> test_lib: direct tests of libspacepy C functions

setup.py, spacepy/data/spacepy.mplstyle, spacepy/data/spacepy_altgrid.mplstyle, spacepy/data/spacepy_polar.mplstyle, spacepy/poppy.py, spacepy/seapy.py, tests/test_poppy.py, tests/test_spacepy.py
SpacePy had a few matplotlib calls that were deprecated a while back, as well as using a color_cycler object in the plot styles. The color_cycler has been replaced with a properties cycler requiring a different syntax in the style file.
The commits in this PR remove or replace all of the deprecated/removed calls to matplotlib keeping us compatible with the latest matplotlib and removing all of the matplotlib warnings that I've hit... This PR resolves #22 
As discussed in issue #8, this also requires bumping the required versions of dependencies, and I've updated the setup.py accordingly.
=> Fixing matplotlib deprecated/removed features

spacepy/pycdf/__init__.py
Found this with mk1 eyeball; it's hit only in very rare circumstances, which is why it hasn't shown up before.
=> pycdf: fix typo 'ctype' instead of 'ctypes'

CHANGELOG, spacepy/pycdf/__init__.py
I couldn't actually reproduce this but that might have been from having to comment a bunch of stuff out to make the triggering script run, or maybe it was just bad luck. This just cleans up a few places that are likely the trigger.
=> pycdf: fix more BAD_ENTRY_NUM (closes #25)

Doc/source/conf.py, Doc/source/doc_standard.rst
Duelling PR here, but I see no reason to pick up a version dependency when we can work around it.
=> docs: Replace pngmath with imgmath (closes #35)

.travis.yml
Updates to the Travis CI configuration.
Specifically, this adds a testing matrix with specified versions of Python and numpy.
- Python 2.7 is now tested. Closes #30 
- Specific versions of numpy are tested. Closes #31 
- The latest release of numpy will also be tested as one matrix member uses constraints, e.g., >=1.6,!=1.15.0
All testing passes. Numpy 1.1.5.0 is specifically excluded from testing due to the issue described in #24 and #30 
For now I've kept the testing matrix relatively small. It can always be expanded as we develop a concrete plan for what needs testing (which I see as a future enhancement, not required to close the issues at hand). This PR provides a blueprint for expanding the testing in the future..
=> Test against specific numpy versions, plus latest release

developer/scripts/win_build_system_setup.cmd, setup.py
With this PR, the Windows build works: setup.py build/install work, bdist_wininst work, and pip install from the git commit.
I haven't run all the unit tests (those will result in separate bugs as necessary) and I haven't tested that the bdist_wininst output actually installs (that's actually pretty hard with several parallel Anaconda environments, as it requires registry hacking, but it will be tested in the future). Also this doesn't close the problem of pip install without numpy, that's unrelated to the Windows build setup.
=> Fix windows build of libspacepy

developer/scripts/build_win.cmd, developer/scripts/win_build_system_setup.cmd, developer/scripts/win_build_system_teardown.cmd
Fixes the win_build_system_setup batch script and adds two new ones: one which builds all the versions of SpacePy, and one which tears down the Windows build system. This allows a build of SpacePy Windows installers for all versions (Python 2.7/3.6 and 32-bit/64-bit) without touching any other installations of Python.
I hate batch.
=> Scripts to do actual spacepy build in Windows

spacepy/coordinates.py
We're exploring using SpacePy to provide the basis for some coordinate transform operations using the Geomagnetic Coordinate System. Being not an expert in the field, I found it hard to work out whether SpacePy could provide such functionality based on the docs, as the supported coordinate systems are provided as abbreviations only.
As such, to lower the future bar to entry for people such as I, I've added a short definition of each supported coordinate. I've also updated the link to the IRBEM docs, as the current link seems to have stopped working.
Note: my sources for providing the definitions of the coordinates were:
* https://www.spenvis.oma.be/help/background/coortran/coortran.html
* https://www.vdl.afrl.af.mil/programs/ae9ap9/files/package/Ae9_Ap9_SPM_Users_Guide.pdf#page=16 (PDF; …
=> DOC: definitions of coordinates 

spacepy/lib.py
Alternative to #77 (although assumes it's applied) and fixes #75. This is the way it was fixed in setup.py and avoids being version-specific. I could probably one-liner it with `ext = sysconfig.get_config_var('EXT_SUFFIX') or sysconfig.get_config_var('SO')` but that seems needlessly opaque.
=> lib: non-version-specific SO deprecation fix

.travis.yml
Added webhooks to Travis CI configuration to have TravisBuddy comment on test failures in PRs.
Syntax following https://www.travisbuddy.com/getting-started.
No comments on tests passing. The comments on test failure *should* say why the test suite failed.
This closes #32
=> travis.yml: added TravisBuddy webhooks for test failure autonotify

CHANGELOG, developer/benchmarks/pycdf/entry_writing.py, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This speeds up code that writes a lot of attributes by about a factor of 3, and would also substantially help out anything that's just hitting a lot of variables. It switches from checking the CDF for a variable/attribute number every time a variable/attribute is referenced to cacheing the number (and expiring the cache when things happen that might change it.)
=> Pycdf attrs speedup (closes #89)

spacepy/irbempy/irbempy.py, spacepy/plot/__init__.py, spacepy/pycdf/__init__.py, spacepy/time.py, tests/test_pycdf.py
This fixes the DeprecationWarning from using the top-level collections for access to abstract base classes, as discussed in #42. Once we drop Python 2 support we can probably go back to properly namespacing.
=> Fix abc imports (closes #42)

tests/test_datamanager.py
Just a test update; filenames aren't guaranteed to be read sorted and datamanager doesn't promise a sort, so sorts both the expected and actual files.
=> datamanager test_files_matching: do not depend on order of filenames

spacepy/datamanager.py, tests/test_datamanager.py
Basically just expiicitly uses POSIX paths (as is the design for RePath), although adds an option for native paths in some low-level utility functions where it might be handy.
=> Fixes for datamanager under Windows

spacepy/pybats/__init__.py, tests/test_pybats.py
Type guessing on Windows leads to a MemoryError when the ASCII file is read using _read_idl_bin.
Summary of changes:
- `spacepy/pybats/__init__.py`: This PR traps for the error, and also wraps the whole `_read_idl_bin` function in a context manager so that the file is closed on raising any exception. *It looks like massive changes, but it's really just the diff not catching the indent for the `with` block*
- `tests/test_pybats.py`: A test is added to make sure the typeguessing doesn't fail.  This previously failed on Windows 10 (Python 3.7.1, 32 bit), but now passes (local tests). Spacepy's Travis suite passes with the new code and tests, but only tests on linux.
This PR resolves #86
=> pybats: trap Window MemoryError reading ascii IDL file with binary assumption

spacepy/pycdf/__init__.py
Just documentation on when closing a readonly CDF might be slow.
=> pycdf: document slow readonly close (Closes #110)

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This fixes a crash caused by tt2000_to_epoch16; the essence is to fix the return value (misdocumented in the CDF C manual, which has been sent upstream.) There's some additional cleanup while I was at it.
=> pycdf: Fix crash in tt2000_to_epoch16 (Closes #60)

spacepy/pycdf/__init__.py
Quick patch that resolves a FutureWarning that shows up in very recent numpy.
=> pycdf: fix FutureWarning on slicing with non-tuple

CHANGELOG, spacepy/pycdf/__init__.py
I found a case where opening a CDF from master meant it was opened read-only and then read-write, which was needlessly slow.
Also put in a documentation note of the ups and downs of readonly; some benchmarking indicates the cache does help things out in some cases, so always opening read-write doesn't seem like a good idea.
=> Pycdf slow ro again

spacepy/toolbox/__init__.py
Number of bins returned by `toolbox.binHisto` has been returning integers values represented as floats.
This behaviour was allowed/tolerated in use cases (including the histogram in the docstring example), but has been deprecated.
This PR casts the number of bins to int, and so closes #100 
This PR also updates the docstring to reflect the returned int and the deprecation of the `normed` keyword in the example plot.
=> Fix toolbox.binHisto nbins to integer, update docstring

CHANGELOG, spacepy/ae9ap9.py, spacepy/pybats/rim.py
Closes issue #59 
Resolves incorrect read mode in Python 2 on Windows. The discussion in #59 includes a reference to a bug report for Python where this was discussed. Using the io.TextIOWrapper as discussed is not a solution as it forces the failure under Python 2.7 to a different spot.
This fix simply tries the original read, and if it fails with a ValueError then it tries to read using the default mode (which gives the desired results on Windows with Python 2). No additional tests are needed as the unit tests that were failing under Windows now pass (Windows 10, Python 2.7.16 (Anaconda)).
=> Fixed gzip read on Windows/Py2.7 (pybats, ae9ap9)

CHANGELOG, spacepy/datamodel.py, tests/test_datamodel.py
Closes #62 
A test failure on Windows highlighted that dtypes were not guaranteed to be consistent across platforms (e.g., numpy might assign `numpy.array([4])` a dtype of int32 or int64). Also, dtypes were not guaranteed to be preserved on creating a recarray from a SpaceData (the default dtype-guessing was being used on creating the recarray, so specified dtypes may not be honoured).
This PR:
- Changes the failing test so that it doesn't check types, just equality of contents
- Adds new tests to check for type-preservation
- Updates `toRecArray` so that it uses the names/dtypes from the SpaceData contents to set the names/dtypes in the numpy record array
- Notes the change in CHANGELOG
Tested on Python 2.7 (64-bit) on Windows, plus everything in the CI.
=> Explicitly preserve dtypes converting SpaceData to numpy recarray

spacepy/pybats/bats.py, spacepy/pybats/qotree.py, spacepy/pybats/rim.py
This PR updates capabilities in the PyBats submodules.  Amongst small quality of life updates for plotting, there are a few substantial changes:
- The quad and oct tree module now properly handles cases where BATS 2D slices passes between two blocks of different resolution.  This fixes issues with loading files, stream traces, and pcolor plotting.
- The Bats2d.add_b_magsphere_new method now replaces Bats2d.add_b_magsphere as the default method for adding magnetic field lines to 2D plots at Earth.  
- The legacy method for Bats2d.add_b_magsphere has been moved to Bats2d.add_b_magsphere_legacy
- Calls to Bats2d.add_b_magsphere_new cause a depreciation warning.
- rim.Iono files have a new method for calculating the integrated FAC strength: Iono.calc_I
=> Batsupdate

spacepy/pybats/ram.py
closes #83 
Fixes a number of issues with ram.PressureFile plotting routines:
- Adding both contour lines and filled contours
- Removing outdated calls to "get_cmap" from within matplotlib contour calls.
- Changed default colormap from jet/spectral to inferno.
- Updated doc strings.
=> Ram contour plot fixes.

spacepy/omni.py
When reading the omni database, open the file so another process can also read from it.
Doing a proper unit test for this got ridiculous, because it would require inserting locking into get_omni to resolve the race condition between the two processes (or just spawning a zillion and hoping.) Opening the file outside of read_omni doesn't work: if opened r/w, then the omni readonly open still fails. If opened ro, then a rw open later on in omni still succeeds. So there's no way to "prepare" the omni read for failure if omni opens rw.
(Open RO, then RO: fine.
RW, then RO: RO fails.
RO, then RW: fine.
RW, then RW: second RW fails.)
=> omni: open the database readonly to accommodate multiprocessing scenarios (Closes #128)

tests/test_pycdf.py
I had a case come up where it looked like cloning a variable didn't maintain the compression. Wrote a test to track it down and looks like it does...this is just including that test to avoid a regression.
=> pycdf: explicitly test that cloning maintains compression

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
I found an instance where passing a numpy array of dtype object but that  contained entirely integers resulted in a float variable being created. This PR improves the handling of object arrays, by trying to convert them to numeric and explicitly raising an error if that is not possible.
This doesn't affect the handling of object arrays containing datetimes, as those are handled before this code is hit.
=> Pycdf more type guessing

spacepy/data_assimilation.py
`matplotlib.mlab` used to supply a number of functions to replicate MatLab functionality and syntax. These were deprecated some time ago. `spacepy.data_assimilation` used `matplotlib.mlab.find`: this was deprecated in matplotlib 2.2 and removed in the latest version.
The removal in the latest version means we're now failing continuous integration.
This PR replaces the call to `find` with `numpy.where` so that the mlab dependence is gone and the fix is compatible even with very old versions of numpy.
This PR closes issue #133
=> Replace defunct calls to matplotlib.mlab in data_assimilation

developer/scripts/build_win.cmd, developer/scripts/win_build_system_setup.cmd
Newer Anacondas changed behaviour and needed some updates to thw Windows build scripts.
* Need to activate base env before doing anything
* deactivate replaced by conda deactivate
=> Windows build updates for new Anaconda

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
CDF library API changed from 3.7.1 to 3.7.0 (new names for CDF_TT2000_from_UTC_parts and CDF_TT2000_to_UTC_parts). Also in a lot of cases the library was returning 9999/12/13 for invalid dates; one of those cases (but not others) has been changed to 9999/12/31 so the test needed to be updated.
=> pycdf: Compatibility with CDF library 3.7.1 (Closes #142)

tests/test_toolbox.py
Loosens up the tolerance on acceptable run times on the long side while tightening on the short side, and modifying the output test to be a little more flexible to change in the future.
Test update only; no actual functionality issues.
Tested in Win7 VM on Python 2.7, 3.6 times 32-bit, 64-bit.
=> Fix test_eventTimer in Win VM (Closes #65)

tests/test_datamodel.py
Closes #63 
In `test_datamodel.py`, the test `JSONTests.test_toHTML` checks for a size. The expected size accounted for the bytes->unicode change from Python 2 to Python 3, but not on Windows systems.
This PR adds a check for the type of the string in Windows, and sets the size accordingly.
This *_only_* changes the test, not the functionality. The previous test was failing on Windows under Python 3 because this case wasn't tested correctly.
=> test_datamodel: account for windows line breaks and unicode differences

spacepy/plot/utils.py
Closes #4.
- Changed a divide on an integer to an explicit `//` so it won't fail in Python 3
- Corrected a typo in the docstring example so that it works with a cpaste into the interpreter
As discussed in #4 the only way I could reproduce the remaining issues in the description was to use non-line-based data. Changing that should be a new enhancement request. (Sorry about the ancient commit, but I forgot I had already committed a fix locally!)
=> Fixed implicit int division in EventClicker

tests/test_pycdf.py
numpy shapes are "long" on 64-bit python 2 (probably because of the 32-bit long issue that's been biting us.) So the string representation has a bunch of "L". This PR makes the check for the error message match whatever representation numpy gives us.
This isn't a functionality issue, just a test.
=> Update testWriteWrongSizeData (Closes #66)

setup.py, spacepy/__init__.py
This changes the Windows installer creation script to also capture the pthread dll, which seems to be required now.
Originally this machinery was meant to get just the Fortran runtimes from mingw32, so there's also a fair bit of renaming to make clear this is now a general dll-grabber.
=> setup: Copy mingw pthread lib to Windows installer.

spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/AE8_AP8.f, spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/CoordTrans.f, spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/drift_bounce_orbit.f, spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/find_foot.f, spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/onera_desp_lib.f
f2py doesn't like exclamation marks on lines with a declaration e.g. INTEGER or a function call (CALL ...).
These _in-line_ comments have now been moved to adjacent lines, so it quiets down a number of the f2py complaints on compilation. There are still a bunch of warnings from the implied do-loops when constructing the data statements in AE8/AP8, but I don't think that should afect functionality. (It'd still be nice to restructure the Fortran to quiet that down too). I've already pushed this change back up to the IRBEM repo on SF. Most of the changes were in functions we don't use (IDL wrapper functions).
This doesn't touch any code _per se_, but may make f2py's job a little easier. In that sense, it might affect test failures like #68 (although it seems unlikely).
=> irbem: moved inline comments on statement lines (for f2py)

Doc/source/help.rst, Doc/source/index.rst
Small documentation update to add links to our github page in the guise of a "how to get help" document. There can be lots of refinements in the future (particularly as we get the website back up on github pages) but this is a start.
=> documentation: Add how-to-get-help document

setup.py
This PR adds support for buliding binary wheels (bdist_wheel). The installation of the wheel has only been tested on Windows but that's the main goal at this point. It's been tested with pip install <name of wheel> not via pypi (testing for that will be later.)
There's a false start of trying to separate out the arch-specific and Python-only bits of the build. This was reverted but not rebased away because I think it's something we should do in the future. Ultimately this is treating everything (including Python code) as arch-specific but that beats treating the compiled stuff as non-arch specific. This is basically the most direct route to getting everything included in the wheel and there definitely should be some more intelligent sorting out later.
=> Support for building binary wheels

README.md, setup.py
This PR removes the requirement for ffnet on Windows so people can install from binary wheel without having a Fortran compiler (for ffnet). This will keep LANLstar from working by default, but explicitly installing ffnet will make that work (without having to reinstall SpacePy.)
This is option 3 on #160 . It it not the only option (or necessarily the one I'm voting for), but it's certainly the _easiest_.
Note this only affects `install_requires` so the metadata still declares an ffnet dependency.
=> Do not require ffnet on Windows

Doc/source/_templates/layout.html, Doc/source/install.rst, Doc/source/install_linux.rst
Install instructions in documentation is old. This PR:
- changes the homepage link in the Sphinx template to point at the github repo (not the defunct LANL page)
- does a light update of the linux instructions
- changes EPD and Python(x,y) suggestions to Anaconda and Canopy
- adds pip to the instructions
- points to source code at github
- leads the generic install instructions with a pip install
- clarifies suggested installation target in and out of virtual envs
- i.e., no `sudo` or `--user` in virtual envs, save those for non-virtual env
It's not a comprehensive overhaul, by any means, but hopefully it takes out the worst anachronisms.
=> Updates to install documentation

Doc/source/install.rst, Doc/source/install_linux.rst, Doc/source/install_mac.rst, Doc/source/install_windows.rst
As discussed in #163 , this splits out the simple stuff ("just run pip") from all the complications. This really only affects Windows and Linux; we really need somebody to do this for Mac.
=> install docs: separate out the simple stuff and all the complications

Doc/source/install_linux.rst
Small docs update to list the Fortran options in Linux (as it is on Mac and used to be in the generic instructions.)
=> docs: add Fortran options to Linux install instructions

DISTRIBUTE, Doc/source/help.rst, Doc/source/install.rst, Doc/source/install_linux.rst, Doc/source/install_windows.rst, README.md
A bit of a mishmash PR but it's all pertaining to release prep.
- Update the DISTRIBUTE document which describes making a release
- PyPI no longer hosts Windows standalone installers, so reference GitHub for those
- pythonhosted is dead so move documentation to github as well. We can always put more of "home page" there later and put the docs in a subdirectory.
=> Release prep

spacepy/time.py
This seems like an upstream issue in sphinx or in numpydoc. But this really minor change allows for the docs to build. Closes #169
=> time.py: minor update to docstring to close #169

CHANGELOG, DISTRIBUTE, Doc/source/conf.py, developer/scripts/build_win.cmd, spacepy/__init__.py
A few commits that do post 0.2.0 release cleanup:
- Version number back to unreleased
- A fix in the Windows build script that appeared after 0.2.0 was tagged anyhow (doesn't affect the built product)
- Some more notes on how to do a release, capturing experience from this time.
=> Postrelease 0.2.0

spacepy/pybats/__init__.py
Closes #186 
As discussed in #186, explicitly cast the calculated record length to int so that adding the numpy int to the start position won't cause an integer overflow on Windows, when attempting to read binary BATSRUS files larger than 2GB.
Tested locally per discussion in #186.
=> pybats: IdlFile/Bats2d: Fix overflow of integer file positions on Windows for large files

spacepy/plot/spectrogram.py, spacepy/toolbox/__init__.py, tests/test_spectrogram.py
This will close #181. The fix is a simple cast to int for the `num` parameter in `linspace` and `logspace`.
=> toolbox: update to close #181. The num parameters are explicitly cast to int

CHANGELOG, spacepy/poppy.py, tests/test_poppy.py
poppy.boots_ci was failing (C version only) if the aggregating function returned multiple values. This PR adds a test and fixes this.
In the case of multiple returns, the result isn't sorted, since there isn't one sort order. This shouldn't affect the results; I think the sorting was largely an efficiency measure
=> poppy.boots_ci: fix handling of multiple return values in C version

CHANGELOG, spacepy/irbempy/NOTES.md, spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/onera_desp_lib.f
Fixes compilation problems in #190 and updates notes on upgrading to new IRBEM (just updated line numbers.) Making this change was already on the IRBEM update checklist but apparently got missed.
=> Fix unicode symbol in irbem source

.github/ISSUE_TEMPLATE.md
This PR adds "What version of SpacePy are you using" to the issue template. Triggered by #190 being an old version.
=> Add 'version of spacepy' to issue template

spacepy/plot/utils.py
`set_target` explicitly specifies loc=111 in the function signature so there's no way to tell if the user asked for 111 or the default. As of mpl 3.1 there's a default location (which does happen to be 111) so this distinguishes between the two call cases.
This also slaps one `type` comparison in favor of `isinstance`.
=> plot.utils.set_target: distingush between loc=111 and loc=default

Doc/source/toolbox.rst, spacepy/toolbox/__init__.py, tests/test_toolbox.py
This PR adds a toolbox function to calculate bootstrap-based confidence intervals on histograms (and optionally plot.) It's nothing earthshattering but I had a student who wasn't putting error bars on a histo and figured it was worth making easy.
=> Bootstrap-based histogram with error bars

spacepy/pycdf/__init__.py
Documents the "virtual records" warning when reading off the end of a CDF. This shouldn't show up with pycdf range checking so it's usually an indication to file an issue so we can reproduce and tighten up the range checks.
=> pycdf: Document virtual records (Closes #109)

CHANGELOG, Doc/source/index.rst, Doc/source/pycdf.rst, Doc/source/scripts.rst, MANIFEST.in, scripts/istp_checks.py, spacepy/pycdf/__init__.py, spacepy/pycdf/istp.py, tests/test_pycdf_istp.py, tests/test_spacepy.py
This PR adds a module specifically for CDFs that use ISTP-compliant metadata (as opposed to CDFs in general). There's more to come but these are the first few useful functions.
=> pycdf support for ISTP-compliant CDFs

spacepy/time.py, tests/test_time.py
Quick error message in Ticktock constructor if can't guess dtype.
=> time.Ticktock: better error if can't guess type (Closes #132)

spacepy/__init__.py
See #18 for rationale. I took a slightly different tack; the comment line now includes the SpacePy version, the key, and the value. That way if people uncomment and edit any particular item in the config file, they have the default above specifically for reference.
So this:
```
#SpacePy 0.2.0 default ncpus: 8
#ncpus: 8
```
then can become:
```
#SpacePy 0.2.0 default ncpus: 8
ncpus: 16
```
=> Write config file default comments on two lines (Closes #18)

Doc/source/configuration.rst
This PR adds documentation of our `support_notice` option (whether to display the "not supported" notice on non-release builds) to the config file documentation.
=> Document the support_notice config file key

setup.py
We were using `std=legacy` for the actual irbem compile on gnu95 but not for the f2py calls. This caused issues e.g. #190 and #204.
This PR adds std=legacy to the f2py calls when using gnu95 in hopes of avoiding these issues in the future.
Ideally we do want to fix irbem code to work without `std=legacy` but in the meantime this PR 1) makes us consistent between library compile and f2py and 2) keeps things ticking along.
=> setup: use std=legacy for f2py on gnu95

spacepy/toolbox/__init__.py
This fixes https://github.com/spacepy/spacepy/issues/218, where it was found that the extracted zip file contents for OMNI2 data download were not cleaned up.
Testing this PR can be done as follows:
1) using the `master` branch, run the command `python -c "import spacepy.toolbox; spacepy.toolbox.update(omni2=True)"` and verify that a file named `OMNI_OMNI2_merged_20120213-v1.cdf` appears, but isn't cleaned up
2) using this PR, run the same command as above and notice that the file is cleaned up
This works in both python 2 and python 3.
=> [BUGFIX]: clean up extracted file

CHANGELOG, spacepy/pycdf/__init__.py, spacepy/pycdf/istp.py, tests/test_pycdf.py
This PR adds information about original CDF type, record and dimension variance, compression, etc. to VarCopy so that new CDF variables made from it will match.
I thought about exposing the information as in the Var objects but there are two problems. One is that the `compress` method already exists in ndarray/dmarray so including it sort of messes things up. I suppose this is workable by a super call if any args are called. The other problem is that things can get a little bit weird if you do really bizarre stuff and then expect it to still work...so for instance slicing out a dimension doesn't update the dimension variance. This isn't trying to be perfect, just carry some information.
I'm a little conflicted on this, as it would be nice to be able to have the same interface for Var and …
=> pycdf: put CDF-specific metadata in VarCopy

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This PR fixes a rather esoteric bug. pycdf accepts writing of "raw" values, most commonly converted Epoch values rather than datetime. With EPOCH16, each value in the CDF requires two numbers on the input, picking up an extra axis of length 2 (in numpy parlance). Most of this is handled properly but, in writing to an attribute, the extra axis wasn't appropriately handled and twice as much data was written.
This fixes the bug. The new test case should be a pretty good illustration of the problem.
=> pycdf.Attr: Fix writing an EPOCH16 Entry in raw mode

CHANGELOG, spacepy/pycdf/__init__.py, spacepy/pycdf/istp.py, tests/test_pycdf.py, tests/test_pycdf_istp.py
This PR makes a few enhancements to the checks in the ISTP module, and one related bugfix
- The "minimum value" calculation for TT2000 was wrong; it returned fill. This is fixed.
- Checks for VALID/SCALE MIN/MAX now check that the type is the same as the variable type (CDAWeb specifically asked for this in some files I was submitting.)
- References to DELTA variables are now checked for existence, match of variable type, and match of units.
=> pycdf istp check enhancements

spacepy/pycdf/__init__.py, tests/test_pycdf.py
Fixes one of the warnings from #224
=> pycdf: Fix some deprecation warnings for new numpy

spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
I can reproduce this but it's hard to describe. When using a single source variable and slicing it two different ways for the output, VarBundle is supposed to detect when a variable needs to be renamed and when it conflicts. In this particular case (which might be connected to the fact that one of the dependencies depends on something else), on Python 3 it erroneously thinks that the Epochs conflict between the two output variables even when there's no slicing on the record dimension.
The path that gets there is complicated but the cause is simple: bytes and strings don't compare equal, so it has to be decoded.
EDIT: To be explicit, this PR fixes the problem. (As well as testing for it.)
=> pycdf.istp.VarBundle: py3k fix for complicated variable-conflict test

CHANGELOG, spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
CDAWeb has asked that character entries not have the null string, e.g. if something is truly unitless it should have a single space for UNITS. This PR adds checks for that in the global and variable attributes.
=> pycdf.istp: Checks for null string Entries in attributes

spacepy/toolbox/__init__.py
This is trivial, but when I updated the default number of bootstrap iterations on bootHisto, I didn't also update the documentation of the default. This fixes that.
=> toolbox.bootHisto: fix documentation of default iteration count

spacepy/toolbox/__init__.py, tests/test_toolbox.py
Closes #183
This PR provides:
- a test for the failures raised in issue #183
- a trap/workaround for the failure mode (objects can't be determined as finite or not)
- a warning on hitting the trap so the user knows that non-finite values may be present
Any suggestions for wording on the warning? Or other implementation issues?
=> toolbox: handle object arrays in pmm (closes #183)

CHANGELOG, Doc/source/pycdf.rst, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This adds a function to pycdf to read data from several CDFs and present it as if it were from one (essentially like a VarCopy from multiple CDFs). It also rearranges the pycdf docs a little bit, since this is the first top-level function. This would be part of the #233 fix.
Definitely open to suggestions on if this should be named something else or put somewhere else.
=> pycdf.concatCDF: function to concatenate data from several CDFs

spacepy/plot/utils.py
`matplotlib.dates.num2date` assumes the system timezone if no timezone is provided.  This can create problems if trying to use `EventClicker` on tz-naive data or data with a timezone different than the system.
This problem can be eliminated by handing the timezone of the data to `num2date`.  If the timezone is `None`, the [incorrect] system timezone is removed by the following line.
I've updated all calls to `num2date` to include the `tzinfo` from `xdata[0]`, and then remove the `tzinfo` from the response if it was `None` to begin with.  (This convoluted order is necessary because `num2date` assumes the system timezone if the `tz` arg is `None`.)
=> Fix plot.utils.EventClicker with non- (or differing-)timezone datetimes, closes #243

spacepy/coordinates.py
Currently the type check in spacepy.coordinate.py is case sensitive. This means that the following coordinate definitions are valid:
```python
from spacepy.coordinates import Coords
p1 = Coords([1,2,3],'GEO','car')
p2 = Coords([4,5,6],'GSM','sph')
```
but the following produce an error
```python
p1 = Coords([1,2,3],'geo','car')
p2 = Coords([4,5,6],'GSM','SPH')
```
which, as far as I can tell, is an arbitrary restriction. By forcing `dtype` to upper case and `carsph` to lowercase early within in `Coord` constructor, this error is avoided without affecting the functionality of the class. Following this change, all of the above examples are valid.
I realise this is a cosmetic change, however it represents a small QoL improvement for those of us who can never remember which way around the …
=> Remove case sensitivity of coordinate type check

spacepy/pycdf/__init__.py
While working on something else I noticed that building the pycdf.concatCDF docs threw "ERROR: Unexpected indentation" even though it built fine. This PR fixed that error (and it still renders properly.)
=> pycdf.concatCDF: fix Unexpected indentation in docstring

spacepy/toolbox/__init__.py
The bootHisto example had an improperly formatted line continuation, so using the "hide prompts" button (`>>>`) removed a continued line. In fixing this, it seemed to make more sense just to use the `include-source` argument of the `plot` directive rather than having the example and then repeating the same code to make the plot.
This also involved renaming the return values in the example to match the documentation (and make them a bit shorter to keep the line continuation in the middle of the arguments, as `\` line continuation is a bit weird in the plot directive.)
=> toolbox.bootHisto: fix formatting of example

spacepy/plot/utils.py
These changes add support to EventClicker for matplotlib.pyplot.pcolormesh (QuadMesh) objects, and should be extensible enough to include any pyplot object that doesn't have line data associated with it.
I've included a new example (that may need reformatting) in the doctstring for EventClicker to show how this works.  EventClicker.get_events_data does not work for a pcolormesh/non-line object, as there isn't any "event data" to grab, but get_events will still get the x-value or datetime (whichever is used for the x-axis) of wherever was clicked.
(Incidentally Github wants to include some of my previous commits from a different PR in this.  I don't know why, nor how to exclude them, but if this needs changing let me know.)
=> plot.utils.EventClicker pcolormesh (and non-line object) support

spacepy/plot/__init__.py
Duelling implementation to #259 . I hadn't realized we already had the submodule list, it just needed to be put into a toctree so it was actually swept up.
Lots of the docs don't build cleanly, but at least they're there. In particular the business of pulling everything into the root plot namespace makes for a huge mess; most of it is probably manageable but the spectrogram module can't be documented because it's smashed by importing the spectrogram class.
=> Expose plot submodule documentation (Closes #242)

spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
This PR addresses #227 with several functions for examining the bundle:
- ``operations`` lists the operations to be performed
- ``variables`` gives the information on the variables involved and their shape on output
- ``__str__`` and ``__repr__`` give a brief view of the variables
I'd be amenable to having ``__str__`` act more like ``CDF``, i.e. include the output size of the variable and print one variable per line. Matter of taste.
Originally ``operations`` and ``variables`` were going to be a single ``inspect`` function but that didn't seem to give any real advantage. A few other things are slightly different from the original description in #227 and unfortunately the commit history does include a few false starts relating to these changes.
In the course of doing this, I also added one …
=> VarBundle inspection functions

Doc/source/conf.py
This was a very simple update to close #263. Python intersphinx moved. Numpy and scipy have not moved. Matplotlib that was shown to timeout worked fine for me today, so maybe just the day. 
- [X ] New code has inline comments where necessary
- [ N/A] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [ N/A] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ N/A] New features and bug fixes should have unit tests
=> Docs: conf.py: update to python intersphinx, closes 263

CHANGELOG, Doc/source/toolbox.rst, spacepy/__init__.py, spacepy/omni.py, spacepy/pycdf/istp.py, spacepy/toolbox/__init__.py, tests/integration_all.py, tests/integration_omni.py, tests/integration_toolbox.py, tests/test_pycdf_istp.py
This PR is a step towards closing #233:
- Completely reworks our downloading in toolbox.update to avoid deprecations. Ultimately this should be replaced by a more robust general downloading infrastructure.
- Switches to the 6-month OMNI2 CDFs from CDAWeb/SPDF instead of the combined from ViRBO
- Fixes a little problem in the omni documentation in specifying OMNI2 database.
=> Get OMNI2 data from CDAWeb

Doc/source/toolbox.rst, spacepy/toolbox/__init__.py, tests/test_toolbox.py
Expands test coverage for quaternion math.
This was motivated by issue #184. That issue is invalid, and should be closed, but to ensure/demonstrate correctness I've added more unit tests.
These tests are:
- quaternion conjugation (for both scalar positions)
- quaternion multiplication (for a simple case)
- quaternion normalization, testing for
- known case, both scalar positions
- near-zero case, both scalar positions
The reason #184 is invalid is that, in essence, the norm of the quaternion (w, i, j, k) is simply (w/n, i/n, j/n, k/n) where n is sqrt(w^2 + i^2 + j^2 + k^2). So the position of the scalar is generally irrelevant in the normalization and the reported behaviour is expected.
The reason that the `scalarPos` kwarg is still present is for handling the case where the quaternion …
=> test_toolbox: additional tests for quaternion math

CHANGELOG, Doc/source/dependencies.rst, Doc/source/index.rst, Doc/source/install.rst, Doc/source/py2k_eol.rst
This PR documents the plan for ending Python 2 support in SpacePy as in #26. The document is linked from the dependencies page (which now recommends Python 3 instead of 2). The install page is updated to more strongly recommend Python 3.
I think we all need to be on board with this so I'm explicitly requesting review from everybody...that can be a review of the plan and/or its presentation in this PR.
=> Document py2k EOL plan (Closes #211)

Doc/source/dep_versions.rst, Doc/source/dependencies.rst, Doc/source/index.rst
This PR proposes a policy for removing support for old versions of dependencies. It tries to capture the discussion in #8 and also be reasonable compliant with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).
The idea is that if we have to bump a dependency version, rather than having a lot of back-and-forth we have a pretty clear line of if it's compatible with this policy and can then move on.
In addition it also makes some minor updates to `dependencies.rst` where it's clearly pathalogically wrong. I probably will open a different PR to finish up #8 but this is also a step towards that.
Until #211 is merged there's a cross-link that will fail, but otherwise this all builds fine. It'll probably also conflict with #211 but I'll fix this up when #211 is merged.
As it's a …
=> Document commitments for dependency versions

.travis.yml
The CI is currently failing to complete as the link location for the NASA CDF library is no longer valid.
This PR addresses that failure by updating the link locations.
Until this is resolved, other PRs will not be testable.
This PR resolves #287
=> Update CDF location in Travis YAML

spacepy/pybats/__init__.py, tests/test_pybats.py
Closes #291 
Repeat of previous PR that had conflicting merges.
Changes writing ImfInput objects to file: sub-millisecond values now use floor when converting micro- to millisecond values instead of round.
A new test has been added to make sure that this works using the example given in the issue.
I want to note @jtniehof's suggestion:
```
t = self.time[i]
ms = int(round(t.microsecond / 1000.))
if ms = 10000:
ms = 0
t += dt.timedelta(microseconds=1000)
out.write('{:%Y %m %d %H %M %S} {:03d} '.format(t, ms))
```
This is an alternative worth discussing, but I am hesitant to nest an `if` statement in a sometimes very long `for` loop.  IMF files can contain upwards of month(s) worth of data at sub-minute resolution, so writing can already be slow.  Worth discussing.
PR Checklist
[ n/a] New …
=> ImfInput now rounds sub-millisecond times on write.

CHANGELOG, spacepy/plot/utils.py, spacepy/pybats/ram.py, tests/test_pybats.py
Updates to the ram module in pybats. Addressing various related issues that arose when designing quicklook plotting for RAM-SCB for the CCMC.
Main changes:
- RamSat now inherits from SpaceData to get its dict-like behaviour (rather than from object and adding dict-like methods)
- Minor updates to docstrings to describe new kwargs
- Overhaul of omnidirectional flux calculation to be more flexible with species names as runs may not have particular species and new species may be added (Also, RAM-SCB has changed how species are named - this change allows for new and old files, plus future additions)
- Masking of bad values in omnidirectional flux calculation updated for robustness.
- Integer divide for finding indices for python 3 compatibility in PressureFile
- RamSat test updated to test …
=> Fixes/modernization of pybats.ram: plotting, python 3, etc.

.github/PULL_REQUEST_TEMPLATE.md
I didn't make an issue for this, so what does this do?
- In the old PR template the text gave an example `This PR resolves issue #1`, which doesn't link the issue because `issue` is between the magic word and the actual issue reference. This has been updated to show correct syntax.
- Experience suggests that the PR template doesn't really give clear instructions on what to write. As far as I'm concerned deviation from the template is fine as long as the information is present and the boxes have been checked (figuratively speaking), but that assumes the pull-requestor has a good idea of what we need to see in the PR description. To that end I added some of our suggestions as checklist items.
- I've given explicit direction in the updated PR template to replace the preamble text from the …
=> Updated PR template to be clearer and fix issue references

spacepy/datamodel.py, tests/test_datamodel.py
Issue #314 shows that calling `toJSONheadedASCII` can overwrite the `datetime` datatypes with the ISO strings that are generated for write.
This PR adds a test for this behaviour, plus two additional tests to ensure that the `_dateToISO` function isn't changing datatypes (which was the root cause of this bug).
This PR also fixes the issue: For non-`SpaceData` types the copy was being squelched in trying to ensure that the input was an array subtype. The coercion is now done on the copied input, not on the uncopied input.
Closes #314 
Note: I haven't added this to CHANGELOG. Can do if review says it warrants its own CHANGELOG entry. Updates to CHANGELOG with multiple PRs active has led to a lot of updating/fixing conflicts in PRs though, so I'm going to leave it this way unless asked...
=> Fix change of datetime dataype in writeJSONheadedASCII

spacepy/omni.py
Very minor update to get rid of a deprecation warning, added a `mode=` to each `h5py.File()` call. Closes #322. 
- [ X] Pull request has descriptive title
- [X ] Pull request gives overview of changes
- [ X] New code has inline comments where necessary
- [ n/a] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ n/a] New features and bug fixes should have unit tests
- [ X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> omni.py: updated calls to `h5py.File()`, closes #322

.travis.yml, tests/test_all.py
#300 is going to require having some actual tests against the top-level `spacepy/__init__.py`. It would make sense to name that `test_spacepy.py` except we're already using the name for our "run all tests" script. This PR renames to `test_all.py` to open up the script name for future tests. (Also updates the copyright line since I was in there anyway.)
I haven't made a CHANGELOG entry because this is pretty dev-internal, but I can imagine people might find it confusing, so suggestions welcome there. (We really don't have anything about our testing in the docs right now anyhow.)
=> Rename test_spacepy.py to test_all.py

spacepy/time.py
Just changes to the Ticktock docstring
* Note that UTC is datetime and thus can't do leap seconds
* Note that Epoch is CDF_EPOCH not CDF_TIME_TT2000
* Remove note on UNIX time changing length of second; this is a Google
interpretation not definition of UNIX time
* Reformat list of time systems as definition list
=> time.Ticktock: Clarify UTC, Epoch, UNIX time systems (Closes #316)

CHANGELOG, spacepy/irbempy/irbempy.py, tests/test_irbempy.py
Issue #330 identifies an untrapped error when using non-IRBEM-supported coordinate systems.
IRBEM assumes that GSE, GSM, etc. are cartesian. `spacepy.coordinates` allows representation of all systems in both cartesian and spherical.
This PR checks whether the system/representation combination is supported by IRBEM, and if not, performs a spherical to cartesian (or vice versa) transform in the preparation of the data structure to pass to IRBEM.
A test has been added to ensure that spherical and cartesian representations give the same answer (and don't raise exceptions).
Closes #330
=> Add conversion for non-IRBEM-supported coordinates in prep_irbem (closes #330)

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This is the first step towards #198, warning the user that the default for backward-compatible CDFs is about to change. Basically if the user hasn't explicitly set backward-compatible one way or the other, this will warn when making a new CDF (if made from a master, the master's backward-compatible carries over.)
The real nastiness is in the test suite, because there's a bug in Python 2.7 that requires some work-arounds to make sure the deprecation warning is really raised. And then the test suite needs to quiet all the places where the tests are assuming the default--thus a second commit to separate that out.
=> Warn if create CDF without making explicit backward-compat or not.

spacepy/toolbox/__init__.py, tests/test_toolbox.py
#338 discussion mentioned that the progressbar occasionally goes over 100%. This PR fixes that. The main change is pretty straightforward (just clamp the value) but there's some other cleanup, which includes rounding the output (but only on display, it won't trigger the 100% line-clear for 99.9%).
=> Fix toolbox.progressbar going over 100%

tests/test_ae9ap9.py
test_ae9ap9.py: small deprication update with a py2/py3 issue around `unittest.TestCase.assertRaisesRegex` (Closes #179)
- [x ] Pull request has descriptive title
- [x ] Pull request gives overview of changes
- [x ] New code has inline comments where necessary
- [n/a ] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [n/a ] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ x] New features and bug fixes should have unit tests
- [ x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
This is a very minor change @drsteve even said in #179 how to fix this.
=> test_ae9ap9.py: small deprication update with a py2/py3 issue (closes #179)

spacepy/toolbox/__init__.py, tests/test_toolbox.py
Right now progressbar forces an extra newline after the output, so if you do:
```
print("About to do stuff")
for i in really_big_iterator:
spacepy.toolbox.progressbar(c, b, t, "Doing cool stuff")
print("Cool stuff completed")
```
You get:
```
About to do stuff
Doing cool stuff ...100%
Cool stuff completed
```
This makes the mutli-part downloads of #338 confusing. This PR removes the extra empty line.
=> toolbox.progressbar: Only print one newline at end.

CHANGELOG, Doc/source/configuration.rst, spacepy/__init__.py, spacepy/time.py, spacepy/toolbox/__init__.py, tests/data/qindenton_daily/QinDenton_20120901_hour.txt, tests/data/qindenton_daily/QinDenton_20120902_hour.txt, tests/integration_toolbox.py, tests/test_toolbox.py
The ViRBO source for the Qin-Denton formatted OMNI files is no longer maintained (#233). This PR adds the daily files from the New Mexico Consortium (used to support Van Allen Probes) to extend up to the present; it is merged with the ViRBO file. Because these are daily files retrieved over HTTPS, and connection setup is expensive, it also adds the ability to reuse HTTP connections between requests. This isn't very simple or robust code, but it's the difference between five minutes to check all the files and thirty minutes. It will always fall back to the previous code if necessary.
This PR also retrieves the leapsecond file from NASA MODIS, as the USNO is still down.
=> Retrieve Qin-Denton and leapseconds from new source (Closes #233)

spacepy/time.py, tests/test_time.py
Ticktock currently fails when the constructor is called with ISO timestrings in a string-like class that isn't actually str. One manifestation of this is in reading times from HDF5 files that were saved in Python 2 in Python 3. This PR fixes that. The Python 2 code is pretty separable from the Python 3 so hopefully it'll be easy to rip out when the time comes.
Note this still leaves the input data alone, not converting it to str. That's consistent with our usual approach in Ticktock but I can see the argument for converting it at construction time.
This seemed minor enough that I left it out of the CHANGELOG, but happy to hear other opinions.
=> time.Ticktock: allow non-str string-like input (Closes #354)

CHANGELOG, Doc/source/pyplots/datamanager_rebin_1.py, Doc/source/pyplots/datamanager_rebin_2.py, Doc/source/pyplots/datamanager_rebin_3.py, Doc/source/pyplots/datamanager_rebin_4.py, Doc/source/pyplots/datamanager_rebin_5.py, Doc/source/pyplots/datamanager_rebin_6.py, Doc/source/pyplots/datamanager_rebin_7.py, Doc/source/pyplots/datamanager_rebin_common.py, spacepy/datamanager.py, spacepy/plot/spectrogram.py, tests/test_datamanager.py
This PR adds a function that allows the rebinning of one dimension of an array by data in another array. The canonical example of this is going from an array organized by sensor number and tagged by pitch angle, to one binned by pitch angle.
This is the type of thing I've found myself doing a _lot_ and nailing it down in general is actually nontrivial.
I think the one thing lacking in the documentation is a full end-to-end example, but since this usually involves big arrays it's hard to come up with a concise example.
=> New function to rebin array by another array

.travis.yml
This PR adds the "-v" flag to the invocation of the unit tests in Travis CI. Every test will then print a line when it starts and when it finishes. This will make it clear which tests are raising warnings, and which tests are hanging. I've been seeing an occasional hang with the Python 3.8 tests and this will help isolate it. I'm also going to be hitting it on my local machine, but it might be related to the Travis setup, so I want that information. And this is useful in general--we only look at the output if it fails, and in that case the detail is helpful.
=> travis CI: run unit tests with verbose flag

Doc/source/index.rst, Doc/source/spacepy.rst, spacepy/__init__.py
The docstring of the top-level spacepy module isn't exposed in our documentation. We have very little there, but I was looking at e.g. the deprecation decorator and it's not linked from the docs. This PR puts it on a footing with the rest of the modules.
=> Expose documentation of top-level module

spacepy/data_assimilation.py, spacepy/datamodel.py, spacepy/empiricals.py, spacepy/irbempy/irbempy.py, spacepy/plot/spectrogram.py, spacepy/poppy.py, spacepy/pycdf/__init__.py, spacepy/radbelt.py, spacepy/time.py, spacepy/toolbox/__init__.py, tests/test_datamanager.py, tests/test_pycdf_istp.py
This PR started to address some warnings in Python 3.8 and apparently random bugs that might be related (#351, #364). I did clean up the handling of the Pool in get_Lstar, which addresses the ResourceWarning in #364 and hopefully the actual hang, and chances are it addresses the hang in #351, since other people are reporting issues with hangs in Python 3.8 when not properly closing multiprocessing Pools (https://bugs.python.org/issue38744) This is 58f2d1d4.
While I was at it, I cleaned some warnings from 3.8 regarding using `is` for comparison to literal (32efecd7), see the [3.8 release notes](https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior), and a whole mess of numpy warnings. I then suppressed some CDF warnings in the CDF tests. The upshot is that the tests …
=> Fixes for python 3.8 and other warnings

spacepy/toolbox/__init__.py
This PR changes toolbox.update to check for the last year in the ViRBO omnibus file, and only starts downloading daily files from NMC from that year. There's still some overlap, but a whole lot less (and this is easier than trying to get things down to the day.)
(EDIT: Closes #373 . Does it not pick it up from the title?)
=> Skip Q-D daily files for years in ViRBO file (Closes #373)

spacepy/__init__.py, spacepy/coordinates.py, spacepy/toolbox/__init__.py, tests/test_base.py, tests/test_toolbox.py
There's a function decorator to easily deprecate a function in the top-level module. This PR makes several improvements:
- Gets the formatting of the wrapped function's docstring correct; indentation used to be based on the first line and that wasn't always right. It was also adding an extra linebreak at the end, which wasn't needed.
- Allows separation between the message in the DeprecationWarning and what gets added to the docstring
- Some work on getting the function signature to carry through. The only real functional change here is a note in the docstring that it doesn't carry through properly in Python 2, but it's a big diff because of an unwrapping of a function-in-a-function that made the operation a lot less clear.
- Fix up the deprecated quaternion functions in toolbox using …
=> Improvements to deprecator decorator

Doc/source/index.rst, Doc/source/release_notes.rst, spacepy/pybats/rim.py, spacepy/pycdf/istp.py
This PR adds release notes to our Sphinx documentation. While we have a CHANGELOG file in the source distribution, people installing from pip aren't going to see that, so it makes sense to capture the most important information in a form that goes into the web documentation. I've also found myself referring back to numpy release docs a _lot_ lately to figure out what changed in what version, so it's useful for the user to have that in one place.
To get this going I had to fix the pybats.rim docs to expose the class/function documentation, and I did fix the autosummary/autosummary/ problem with pycdf.istp that I mentioned in #378.
=> Create release notes document

Doc/Makefile
Autosummary sources are autogenerated, and the check for updated docstring inputs isn't always perfect. "make clean" should remove all intermediate/automatic steps to ensure a clean build from scratch, so this PR adds removing the autosummary sources.
Yes, there are two nested directories of "autosummary"; it's because a toctree is being defined twice, but fixing it breaks the doc build, so that's going to have to wait for a more involved docs overhaul.
=> Doc Makefile: remove autosummary source files with "make clean"

.travis.yml
This PR is a quick workaround for #381 until it's properly fixed. It just installs older matplotlib in our CI so that the 3.3 change doesn't bite us. Hopefully it'll go away soon, but in the meantime #381 is blocking us from getting anything done.
=> Disable matplotlib 3.3 in CI

CHANGELOG, spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
This...grew.
Initially the concern was that the check for data in the file being within VALIDMIN/VALIDMAX threw an exception when the FILLVAL was of the wrong type. (I was testing a file that had a string for FILLVAL in a numeric variable....don't ask.) So as a result:
- VariableChecks.validrange now will complete with a bad FILLVAL rather than throwing exception.
- New VariableChecks.fillval to see if there _is_ a valid FILLVAL. This sort of duplicates funtionality in the existing NASA ISTP checks, but I think it's important because otherwise the validrange checks (which it can't do) won't necessarily return reasonable values.
- Suppressed some CDF warnings in the tests while I was here.
- Noticed FileChecks.depends didn't end a sentence with a period, so took care of that
- Got sick of …
=> Various enhancements to pycdf.istp compliance checks

Doc/source/publications.rst
This one's my fault...an errant copy-paste for the publications list in #347 introduced stray Unicode, which breaks the LaTeX documentation build. This PR changes that one character to fix it.
=> Doc: publications: remove stray Unicode so LaTeX builds.

CHANGELOG, spacepy/datamodel.py, tests/test_datamodel.py
Fixed the datamodel.SpaceData.toXXX method calls. 
`functools.partial` had been used incorrectly from the beginning and needed to be fixed. Only some cases caused the issue. None should now. 
Also removed code checking for a really old python bug, https://bugs.python.org/issue4380. 
Tests added that cause the cases in #404 
- [X ] Pull request has descriptive title
- [ X] Pull request gives overview of changes
- [ X] New code has inline comments where necessary
- [ X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ X] New features and bug fixes should have unit tests
- [ X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Fixing the datamodel.SpaceData.toXXX method calls, closes #404

Doc/source/pyplots/datamanager_rebin_1.py, Doc/source/pyplots/datamanager_rebin_2.py, Doc/source/pyplots/datamanager_rebin_3.py, Doc/source/pyplots/datamanager_rebin_4.py, Doc/source/pyplots/datamanager_rebin_5.py, Doc/source/pyplots/datamanager_rebin_6.py, Doc/source/pyplots/datamanager_rebin_7.py
This PR adds explicit axis limits to the example code for datamanager.rebin, so closes #402. Whether or not this was an issue depended on what version of matplotlib you were using, but in some cases the axis limits were set way out and there was lots of whitespace. I didn't add the limit setting to the example code in the docstring, just the behind-the-scenes code that actually renders the plot.
=> datamanager.rebin example: specify axis limits (Closes #402)

Doc/source/dep_versions.rst, Doc/source/dependencies.rst, requirements.txt, setup.py, spacepy/coordinates.py, spacepy/datamodel.py, tests/test_time.py
This PR updates the documentation of what dependencies are required and thus closes #365 . In the process I also removed a few workarounds for earlier versions of dependencies which are no longer supported (I didn't do an exhaustive search, just grabbed the quick ones I remembered) and updated the table of how we choose what dependencies to support.
=> Update dependency version documentation

.travis.yml, CHANGELOG, Doc/source/dep_versions.rst, Doc/source/dependencies.rst, Doc/source/images/ticktock_relationships.svg, Doc/source/release_notes.rst, setup.py, spacepy/time.py, tests/test_time.py
This PR adds support for the AstroPy time object. It can be passed to the Ticktock constructor, and a new .getAPT() method and .APT attribute will return AstroPy time.
EDIT: I keep on forgetting the title doesn't work for this. Closes #321 
A few things to note:
1. AstroPy is added as a dependency in the documentation and the CI, but it is _not_ added to setup.py or requires.txt. Installing AstroPy adds no functionality to SpacePy; it's only of interest if you want to work with AstroPy. In which case, chances are you have AstroPy and don't need SpacePy to ask pip to install it.
2. Some combinations of Python 3 version + AstroPy version will throw a ResourceWarning from the tests. This is an AstroPy problem; merely importing AstroPy 1.1.1 on Python 3.5.2 with warnings set to 'always' will …
=> Support Ticktock to/from astropy.time.Time (Closes #321)

.travis.yml, developer/scripts/test_all.sh, spacepy/omni.py, spacepy/pybats/bats.py, tests/test_pybats.py
This PR selects specific versions of all our dependencies so that we're explicitly testing the oldest supported version of everything. This includes rearranging how the pip installs are done so we get the requested version of numpy (Closes #366). By necessity this also gets the pybats tests working on matplotlib 1.5.1 (Closes #421). And to help make it all work there's a quick shell script that builds conda environments and runs the tests in them, basically mimicking CI so we don't have to open a PR to test against a bunch of versions. Oh and it fixes omni and omni-related tests when running the tests with a working directory other than the test directory.
=> CI testing of supported dependency versions (Closes #366) (Closes #421)

spacepy/omni.py
fe42d8a4e138e7a4a2cc12fabdd1d301b98d499e switched away from using RDT to determine the start/end time of an omni database, in favor of UTC. Unfortunately UTC is not stored in the OMNI2 HDF5 files, but generated on read. This PR tries (in order) UTC, Epoch/ISO string (for OMNI2), and RDT (as a fallback.)
This isn't possible to unit test since we don't require a downloaded current OMNI2 database for unit tests. However, without the fix integration_omni.py should fail (and succeed with.)
=> Fix handling of OMNI databases without UTC

spacepy/toolbox/__init__.py
toolbox.get_url tried to be fancy and use strptime %a and %X to parse the last modified headers. Unfortunately those formats are locale-dependent, whereas the http headers are universal. This PR changes the parsing to specify the format and avoid locale-specific names for months and day-of-week.
This isn't something that can be really handled with a unit test, but running `integration_toolbox.py` (the integration test) with a locale set to something that uses e.g. 12-hour time or non-English names should fail before this PR and pass after.
=> toolbox.get_url: fix last modified dates on locales other than C

CHANGELOG, Doc/source/release_notes.rst, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This PR adds warnings and documentation that the default time type will change from CDF_EPOCH/CDF_EPOCH16 to CDF_TIME_TT2000 in the next release, per #198.
=> pycdf: warn default time type is about to change

.travis.yml, developer/scripts/test_all.sh
This PR changes the Travis CI config to build the latest 3.8.0.1 version of the CDF library (the tarball is labeled 3.8.0 but the library reports as 3.8.0.1). pycdf has been tested against this version (Closes #400)
Note that at this point (and even with #422) we're only testing against the latest CDF library, not earlier ones, but that's a question for another day (#423).
=> Update CI to CDF 3.8.0.1 (Closes #400)

CHANGELOG, Doc/source/release_notes.rst, Doc/source/toolbox.rst, spacepy/toolbox/__init__.py, tests/test_toolbox.py
Leftover doctest at the bottom of toolbox, hasn't worked since before 0.1.5. 
Also some code was checking for <numpy 1.3 which is a lot older than we support. 
None of the other modules have it, I propose removing it. 
(JTN: Closes #414)
=> toolbox: remove broken doctest

CHANGELOG, spacepy/toolbox/__init__.py, tests/test_toolbox.py
`bootHisto` accepts a `seed` argument to specify a seed for the RNG. Unfortunately this was not properly passed through to the underlying bootstrap function, which made `bootHisto` nondeterministic even on a single machine with a constant seed. The tests used this functionality to avoid random failures; since this didn't work, there was a cron job CI failure on master.
This PR passes through the `seed` argument properly. This results in a slight shift in the expected value in the tests, since the seed  is now being applied in the test.
=> toolbox.bootHisto: use RNG seed; make test deterministic.

README.md, tests/test_coordinates.py
Resolves #431 
Changes:
- A workaround in `test_coordinates` for `numpy` versions < 1.8 is no longer required as SpacePy's minimum supported version is now 1.10. The workaround has been removed.
- The dependencies list in `README.md` has been updated in line with the `requirements.txt` and the docs.
Checklist:
=> Update dependency versions in README and remove legacy numpy workaround in tests

CHANGELOG, Doc/source/release_notes.rst, spacepy/data_assimilation.py, spacepy/irbempy/irbempy.py, spacepy/radbelt.py, spacepy/toolbox/__init__.py, tests/test_toolbox.py
This PR marks `toolbox.feq` as deprecated, notes such in the release notes, and replaces all SpacePy usage of `feq` with `numpy.isclose`, closes #412.
`feq` and `isclose` have different values for `rtol` (`precision` in `feq`), but I have not put in an explicit `rtol` in every new `isclose` call to keep them identical. It appears that all the `feq` calls were a general "should be exactly equal but, hey, it's floating point" not "the 5e-7 tolerance is exactly what I was looking for."
=> Deprecate toolbox.feq (Closes #412)

tests/test_pycdf_istp.py
This PR cleans up a pycdf ISTP test that was emitting a deprecation warning. The code's okay with choosing any time type, but a `DeprecationWarning` is thrown right now because the default is changing (#426). This just suppresses the warning until we're through the transition  (#198).
=> test_pycdf_istp: suppress a deprecation warning that we know about

CHANGELOG, setup.py
irbem didn't build on Raspberry Pi because the `-m32` bit-size option isn't supported on Pi. This PR fixes that by just nixing that compiler option on ARM. It's possible other ARM systems might support this, but even then they might not require this. If necessary, in the future we can do a direct gfortran call for a toy program with the flag and if it fails, remove it. For now, though, this is a straightforward solution that works. Closes #23.
In the process I added another line of output so it was clear when the IRBEM build started vs. the intents stuff.
The irbem tests run with this fix (currently running other tests; if they fail, that will likely be a separate issue.)
Thanks to @scivision for help in debugging this as part of a PyHC hackathon.
=> Fix irbem build on Raspberry Pi

spacepy/datamodel.py, tests/test_datamodel.py
- [X ] Pull request has descriptive title
- [ X] Pull request gives overview of changes
- [ X] New code has inline comments where necessary
- [ n/a] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ X ] New features and bug fixes should have unit tests
- [ X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
Increased unit test coverage for `datamodel.py`, see #305 and #438
=> Increased test coverage of datamodel.py

spacepy/time.py
I still don't understand why this has only recently become an issue but this fixes it and is correct anyway. Closes #451. 
The see also in docs should not be an evaluated function. `datetime.date.today()` vs `datetime.date.today`
=> time.py: fix doc issue crashing sphinx in come cases

CHANGELOG, Doc/source/configuration.rst, Doc/source/install.rst, Doc/source/release_notes.rst, spacepy/__init__.py, spacepy/omni.py, spacepy/time.py
This PR removes several messages that show up on SpacePy import and changes a few others to warnings. Closes #346.
- Docs are updated to make information about `DOT_FLN` and the `.spacepy` directory more obvious so this information is apparent despite the loss of the first-import message (ac9db898ba1a1bfd9d88d1091c355ea09d648cb7)
- The no OMNI data message is now a warning (trappable) instead of a print statement (a3e41372a1d513354c82908ec084fe351baa6d60). In order to make this less of a mess, this no longer distinguishes between "no HDF5 OMNI data" and "no OMNI data at all" (546a7c01fb6ed6c9985830b45226589fb60fcc20); we stopped using the pickle in 2013 (195704003a775e59726e09a675726e2330eeb7f4).
- To compensate for not having a general `update` message on first import, `time` now checks …
=> Remove on-import messages; change others to warnings

setup.py
#433 fixed the build on Raspberry Pi by doing a `uname` check. Windows doesn't have `uname`, so this broke the build on Windows. Didn't catch it because #55. This PR just checks for Windows before checking uname.
No changelog/release notes entry because this wasn't released.
=> setup: Skip the Raspberry Pi check on Windows

CHANGELOG, spacepy/pybats/ram.py, tests/test_pybats.py
In `spacepy.pybats.ram.RamSat` the `add_omniflux_plot` method produces MLT labels that are offset by 12 hours (i.e. offset of pi radians in the azimuthal coordinate.
The issue was found when plotting simulation output and comparing to Van Allen Probes. It can be reproduced with the test file though.
Inspecting the test file `tests/data/pybats_test/ramsat_test.nc` the approximate SM position is [-1.78, -4.58, -1.17]. Since X is positive sunward and Y is positive duskward, this should imply an MLT in the morning. Calling `_orbit_formatter` yielded an MLT label of `16:35 MLT`.
The new fix:
1. removes the custom MLT calculation and calls `spacepy.toolbox.rad2mlt`.
2. adds a test to check that the output string for plot labeling is as expected given the test file
=> Correct MLT labeling in pybats.ram.RamSat flux plots

CHANGELOG, setup.py
This PR updates setup.py to help it find f2py versions that are "hidden" by MacPorts' `select` command.  It uses sys.version_info to build more f2py* and f2py-* paths that are searched in `default_f2py`.
Additionally, a tabbing error was corrected to reduce redundant searches.
This pull closes #456.
- [ x] Pull request has descriptive title
- [ x] Pull request gives overview of changes
- [ x] New code has inline comments where necessary
- [ x] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> setup: Find f2py when hidden by Macports 

CHANGELOG, spacepy/pybats/__init__.py, tests/test_pybats.py
`pybats.parse_filename_time` assumed the path separator was a `/` and thus broke on Windows. This PR adds a test for that case and fixes the problem with `os.path`.
=>  Fix on pybats filename parsing on Windows for filenames w/directories.

tests/test_spectrogram.py
`test_all.py` is used as the main test runner, when called from `test_all.py` the `spectrogramDateTests` class wasn't being run.
This masked the failure of that test due to the update of the reference epoch in `matplotlib.dates`.
This PR:
- adds `spectrogramDateTests` to the `__all__` so it gets called from the master runner
- sets expected date numbers for bin edges using `numpy.linspace` rather than hardcoding, so the epoch used doesn't break the test
- re-enables the `assert_allclose` testing that was disabled in 8b083f06d6b6d45eff0e064bfe6fc2bfd38437ab for numpy 1.4 compatibility
=> Update spectrogram tests for main test runner

spacepy/time.py
Really minor update to _days1958totai() to Close #462 , I greped around and `np.integer` and `np.float` to not appear anywhere else in the code base. 
I cannot think of a good way to add a unittest for this. I'm all ears if anyone has ideas.
=> time: minor update in _days1958totai(), Closes #462

spacepy/empiricals.py, tests/test_empiricals.py
`getPlasmaPause` now raises `RuntimeWarning`, closes #474 
Unit test added, minor enough did not modify CHANGELOG
=> empiricals.py: getPlasmaPause() raising a warning rather than a print

tests/test_empiricals.py
Closes #484 
Utilize the test OMNI data rather than assume OMNI data are installed.
=> test_empiricals.py: updating test test_getPlasmaPauseCA1992warn

Doc/source/empiricals.rst
This PR adds `getMagnetopause` to `empiricals.rst` so it shows up in the docs.  Closes #489
=> empiricals: expose getMagnetopause in docs

.github/workflows/ci.yml
A GitHub actions workflow won't show up in the UI until it's merged to master and run a single time. This is a very simple workflow that just checks out the repo and does nothing else, so we can merge it to master and activate the workflow. After that, workflow updates in PRs should run properly, which will allow me to complete #495 and ultimately close #455.
This was tested by merging to master on my fork and verifying the action showed up (then force-pushing to my fork to clean up, which won't be necessary here.)
=> Simple GH actions config to make the workflow show up

CHANGELOG, Doc/source/release_notes.rst, spacepy/toolbox/__init__.py, tests/test_toolbox.py
[bootHisto](https://spacepy.github.io/autosummary/spacepy.toolbox.bootHisto.html#spacepy.toolbox.bootHisto) is supposed to pass kwargs through either to `numpy.histogram` (for kwargs it recognizes as such) or `plt.bar`. Unfortunately this was never tested and so, of course, it never worked. This PR adds a test and fix.
While I was at it I documented the version where this function showed up. I didn't retroactively fix the release notes because that will probably require some further overview in the future anyhow.
=> Fix bootHisto kwarg passthrough

tests/test_pycdf.py, tests/test_pycdf_istp.py, tests/test_spectrogram.py
We had several tests that either checked code which used to issue a warning and wanted to make sure it was fixed so it didn't issue that warning, or where we were verifying that the code was issuing a warning it was supposed to. Unfortunately they were implemented as "issues no warnings at all" or "issues exactly one warning that matches what we expect." numpy 1.20 deprecates a bunch of stuff so suddenly there are a lot more warnings and these tests fail. This is why the cron CI run fails.
This PR tightens those tests so they check for only what we really care about: a particular warning is or is not issued.
=> Fix various tests for specific numbers of warnings

CHANGELOG, Doc/source/release_notes.rst, spacepy/time.py, tests/test_time.py
This PR fixes the leapsecond out-of-date warning and also adds tests (since clearly coding it blind without tests was not the way to go.) Closes #473.
I went ahead and put in a release notes entry for it in the "major bugs" section; which is overkill but it's also a highly visible bug.
=> Fix paranoia of leapsecond out-of-date warning

CHANGELOG, Doc/source/release_notes.rst, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This PR adds support to the CDF Sparse Records modes in pycdf. It mainly defines the `Var.sparse_records` wrapper to get and set the Sparse Records modes. When a variable is set to any sparse mode, the check for out of range record index is skipped, so it's possible to set data to any record.
This PR also adds a `pad_value` function to get and set the pad value for a given variable, which is important for the PAD_SPARSERECORDS mode.
=> Adding Sparse Records support to pycdf

CHANGELOG, spacepy/pycdf/__init__.py, tests/test_pycdf.py
datamodel.toCDF makes a _copy_ of the input data and tries to write that:
```python
foo = outdata.new(key, SDobject[key][...], recVary=False)
```
I don't know _why_ it does this but the result is that it makes a _copy_ also of the sparseness type, rather than using the exact object from `pycdf.const`. That means `sparse`, which is checking for the actual object, doesn't recognize it as a valid type.
This PR updates `sparse` to accept any ctypes long or a just plain number, which fixes the problem. It no longer checks for valid sparseness itself--that's left to the CDF library itself.
Closes #512.
EDIT: Also now uses the default compression parameter, rather than the compression parameter from the input data, if a compression type is passed as an argument to `CDF.new()`. Also discussed in …
=> Fix toCDF sparse record handling from CDFCopy

CHANGELOG, pyproject.toml, setup.py
Newer versions of pip support installing build dependencies before trying the build, so for instance people don't need to install numpy before installing SpacePy from source via pip. This is a re-open/extension of #440, which got erroneously closed by GitHub being overzealous about the definition of "merged." See discussion there for details.
EDIT: Closes #173
=> PEP 517/518 support for install numpy before build

Doc/source/conf.py, tests/spacepy_testing.py
#506 changed the unit tests and documentation to use the `build` directory in preference to normal Python paths. Since versions of Python differ in whether they put the version number in subdirectories of `build`, that code first adds the version-specific directory, and then any non-version-specific directories it finds. However, because this is _prepended_ to the path, adding the version-specific first means it's a _lower_ priority. This PR fixes that: the end result is to have version-specific directories first i the path, and non-version-specific second.
=> Fix priority of pathing when using build directory for tests/docs

tests/spacepy_testing.py, tests/test_pycdf_istp.py
This PR clears up three warnings that arise just within the test suite; no changes to the main code.
One is because numpy slightly changed the wording of a warning that was raised when calculating an expected value in a test. The warning was trapped but the new wording wasn't caught, so that was updated.
The other two are from #426; the tests create time variables without specifying a type, so there's a warning the default is going to change. Cleared up by specifying a type.
Closes #515. Closes #516.
=> Clear up warnings in CDF ISTP tests

CHANGELOG, Doc/source/release_notes.rst, spacepy/plot/__init__.py, spacepy/plot/colourmaps.py
The colormaps provided by SpacePy have been in matplotlib since at least 1.5 and attempting to register them breaks on matplotlib 3.4 (#525), so this PR deprecates them and does not register them with matplotlib. Closes #525.
=> Deprecate colourmaps; fix plot on matplotlib 3.4

CHANGELOG, Doc/source/release_notes.rst, developer/scripts/rubber_seconds.py, spacepy/time.py, tests/test_time.py
This PR applies the post-1972 leapsecond rules from 1958 to 1972 and thus closes #393. Background discussion of the problem is in that issue. It also gracefully handles a missing leapsecond file and closes #435.
The fix for #435 isn't easily unit-testable so it was confirmed by hand.
=> Handle leapseconds pre-1972

spacepy/pybats/__init__.py, spacepy/pybats/ram.py, tests/test_pybats.py
The `spacepy.pybats.ram.PressureFile.add_cont_press` method was failing as the plot routines called internally make boolean masks from the array passed in. This is one of the cases where dmarray will not behave correctly (broken numpy subclass behavior that's not trapped by our wrapper), so the plot fails.
So this PR:
1. Adds basic tests for the `add_cont_press` and `add_pcol_press` methods to ensure they'll actually make plots without erroring. It also tests the return types.
2. Makes a couple of fixes for new matplotlib warnings
- `zmin` and `zmax` kwargs are moved into the norm for the `add_pcol_press` plot call.
- `np.int` is a deprecated alias for `int` and this was changed on line 1915 of `pybats/__init__.py`
3. Trailing whitespace stripped from `pybats/__init__.py`
4. I haven't …
=> Fix contour plot method (add_cont_press) in pybats.ram.PressureFile

CHANGELOG, spacepy/irbempy/irbempy.py, tests/test_irbempy.py
This PR will close #537 and close #549
What this PR does:
- In the chunking of user-supplied OMNI values the Qbits were previously being assigned to a dict-like that didn't exist. This has been corrected.
- A check has been added to skip the Qbits if not present (which may simplify user-supplied cases).
- The list of chunked OMNI values wasn't being broken up to be passed to each pool worker, the list is now wrapped in the `zip` to ensure the chunks are paired correctly.
- The numbering of the final index in each chunk has been simplified (per #537). While I haven't been able to identify specific cases where the old code fails, the change here is simpler and always uses the last index rather than using a double-length block to ensure we index _past_ the last item. It's more readable at …
=> Fix OMNI handling and chunking in multi-processed Lstar calculation

CHANGELOG, Doc/source/dependencies.rst, spacepy/coordinates.py, tests/test_coordinates.py
For your consideration, this PR enables interacting back and forth with the Astropy coordinates framework (which is also used by SunPy).  It adds the following methods to `Coords`:
- `to_skycoord()` is a regular method which creates an Astropy `SkyCoord` instance from a `Coords` instance
- `from_skycoord()` is a class method which creates a `Coords` instance from an Astropy `SkyCoord` instance
The conversion utilizes the GEO coordinate frame, which is common to both libraries.
=> Added Coords methods to convert to/from Astropy SkyCoord instances

Doc/source/dep_versions.rst, spacepy/coordinates.py
This PR makes a few documentation updates, relating to discussion in #286.
- Notes that the Coords units arguments aren't really used to do conversions.
- Update the dependency support matrix. The universe packager of AstroPy actually dropped a newer version in an LTS release, which was the reason for the disconnect there, but did a general scrub.
- Made a note in the dependency support docs that these are minimum supported versions, not recommended.
=> Documentation updates for dependencies and Coords units

.github/workflows/ci.yml
This PR updates all our CI jobs to use Ubuntu 20.04, and closes #550.
The first commit is all that really matters: Python 3.5 was added to the GHA environment on Ubuntu 18.04, and so all that was needed was to move to 18.04 instead of 16.04.
That, however, got me down a deep rabbit hole, much of which has been rebased away. 18.04 also supported Python 3.4 in GHA, so I added that to the CI. Finally, I moved the CI to 20.04, which works fine except it doesn't support 3.4, so that was dropped. I could have kept it on 18.04, I guess, but this seemed like more fun.
A lot of the flailing that was rebased away was trying to use the deadsnakes PPA so we had that in our back pocket for CI on older versions. It's actually really hard to use directly in GHA. There's an action for using it directly, …
=> Update CI to 20.04 (Closes #550)

CHANGELOG, Doc/source/release_notes.rst, developer/scripts/build_win.cmd, developer/scripts/win_build_system_setup.cmd, developer/scripts/win_build_system_teardown.cmd, setup.py
This PR does two things:
- Tries to be better about running setup if there are spaces in paths. This comes down to improvements in setup.py to handle pathing better on the one hand, and doing some escaping in the Windows build scripts. Unfortunately this doesn't completely allow for things working properly if the Miniconda path has spaces in it, so this also changes the Windows build scripts to install in the system drive root rather than the user profile directory. As best as I can tell the remaining issues are mostly on f2py/numpy, not SpacePy.
- Doesn't try to define the `bdist_wininst` command unless that was actually passed to `setup.py`. Closes #530. If anybody's unusual enough to explicitly use pip to call `bdist_wininst`, yes, that will probably fail...but that's on them. …
=> Only define bdist_wininst if it's being used (Closes #530)

tests/test_toolbox.py
Tests are currently failing on one of our CI configs due to a few `assert_equal` being applied to float arrays.
This updates `test_interpol_baddata`, `test_interpol_keywords`, and `test_interpol_arb` to consistently use `assert_almost_equal` and to tidy up code that wasn't particularly close to PEP8.
- [N/A] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Change comparison to almost equal on toolbox.interpol tests

.github/workflows/ci.yml, DISTRIBUTE, developer/scripts/build_win.cmd, developer/scripts/test_all.sh, developer/scripts/win_build_system_setup.cmd, developer/scripts/win_build_system_teardown.cmd, spacepy/pycdf/__init__.py
This PR updates our CI, developer test scripts, and Windows build instructions (for developers building distributions) to include Python 3.10, now that both Python 3.10 and supporting versions of scipy and numpy are out. This also includes minor tweaks to the minimum/maximum version of numpy in CI.
EDIT: Two more changes were required:
- To get 3.10 to not be interpreted as a number (3.1), all Python version numbers are now quoted in CI.
- h5py has switched to requiring a specific version of numpy that is tied to the specific version of Python. In addition to being a royal pain in the neck, no numpy version was specified for Python 3.10 until h5py 3.6, so h5py 3.6 is now the minimum tested on 3.10.
EDIT: Also updated the URI for the CDF library on SPDF, in several places.
=> Testing and instruction updates for Python 3.10

Doc/source/pycdf.rst
Simple documentation one-liner. People were getting confused about the specification of time types when creating a new variable by assignment. I added a reference to the `new` method, which lets the user specify the type, at the point where they were getting confused.
At some point I do want to scrub all the pycdf docs but trying to dispose of some virtual post-it notes here...
=> pycdf docs: reference new() in discussion of default time types

.github/workflows/ci.yml, Doc/source/ci.rst, tests/test_coordinates.py
CI is currently failing due to AstroPy and I think it's because there was a glitch at exactly the time our dependencies were rebuilt for the week. There's no way to force-expire the dependency cache to check that. This PR modifies the cache keys to include a reference to a repository-wide secret. We can change that secret to force-expire all dependency caches.
While I was diagnosing this I also found that `test_coordinates` imports `spacepy_testing` (which sets up the pathing) after `spacepy.coordinates`. This meant the `coordinates` import would not come from the build directory. This wasn't showing up in CI because `test_all` fixes the path immediately, but I fixed that for testing `coordinates` on its own.
=> Add cache-expiration to CI

spacepy/datamanager.py, spacepy/datamodel.py, spacepy/plot/spectrogram.py, spacepy/pycdf/__init__.py, spacepy/pycdf/istp.py, spacepy/toolbox/__init__.py, tests/test_datamanager.py, tests/test_pycdf.py, tests/test_time.py, tests/test_toolbox.py
Fixes several deprecation warnings that were showing up in the test suite, from numpy 1.20 and 1.21 and Python 3.9. Most were pretty straightforward.
The pycdf one (#460) is a bit icky because the code is there to work around the original numpy issue, which _warns_ that it will change but hasn't actually been fixed yet. So in that case I just trapped the warning in the test suite; users who trigger that code will get a ValueError along with their deprecation warning.
The other icky one was Python 3.9 deprecating our workaround for the Python 2 and Python 3 RNGs not returning the same values.
Closes #460. Closes #580.
Verified the `toolbox.update` behaviour of #580 by running manually.
=> Fix various numpy and Python deprecation warnings in tests

Doc/source/release_notes.rst, spacepy/__init__.py
This PR reverts the default leapsecond source to the USNO and documents that change. Closes #341.
Verified running `update()` with this change and tests passed after downloading the new leapsecond file from USNO.
=> Revert to USNO for leapseconds

Doc/source/pycdf.rst, Doc/source/release_notes.rst, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This PR lumps together several small pycdf improvements:
- In connection with the new NASA CDF interpretation, support for UTF-8 encoding and documentation of how the encoding works. In addition to switching to utf-8 instead of ascii encoding, this also changes the behavior on decoder fail: silent replacement instead of raising exception. Closes #555. Closes #586.
- Tests truthiness of variables and documents this trick. Closes #560.
- Updates the documentation on slow closing of readonly CDFs, since 3.8.1 fixed this.
=> pycdf enhancements: UTF-8, truthiness, document slow readonly closing

Doc/source/index.rst, Doc/source/release_notes.rst, setup.py, spacepy/__init__.py
This PR removes the documentation which is installed with the library (in the `data` directory), simplifying the installer. `help()` is updated to load the website. Closes #597.
To help with version matching, `help()` prints the user's SpacePy version, and the version is included in the first heading on the main SpacePy docs page.
The release notes go into (probably too much) detail on how to find/download documentation.
=> Do not install docs with SpacePy

spacepy/plot/spectrogram.py
The `plot` method in `spacepy.plot.Spectrogram` defaults to log-scaling the colormap. However, it's using syntax that's no longer allowable by passing `vmin` and `vmax` to `pcolormesh` separate from the `LogNorm` normalizer. From matplotlib 3.3 this issued a warning. From matplotlib 3.5 is raises an error.
This fixes the issue by moving the colormap limits inside the `LogNorm` instance (as is already done in, e.g., `simpleSpectrogram`.
Closes #610 
Spectrogram does need some attention paid to the internals, and there's an issue that needs to be filed to ensure that `add_data` works when the times are specified as datetime objects. However, those are bigger efforts that don't hit a breaking change...
- [N/A] Any new modules, functions or …
=> Fix log-scaled spectrogram plot call for matplotlib >=3.5

Doc/source/release_notes.rst, developer/scripts/pycdf_load_test.py, spacepy/pycdf/__init__.py, tests/test_pycdf.py, tests/test_pycdf_istp.py
This PR update the C function argument handling for pycdf, which fixes 64-bit ARM (Apple Silicon/M1 Mac, but also 64-bit RaspPi). Closes #546.
* Types of fixed arguments are always specified; types of non-variadic arguments are never specified. ctypes is smart enough to treat specified arguments as fixed and the rest as variadic (the typepunning is still required on 32-bit ARM though).
* Argument/return value handling is generalized to make this easier to change in the future.
* Where function arguments are specified, a lot of explicit casts have been removed, relying instead on the ctypes automatic casting. This should make the code easier to read.
In order to do this, I wrote a very simple script that just tests loading and calling the C library. The full test suite isn't very …
=> pycdf 64-bit ARM (M1, 64-bit Pi) support

spacepy/pybats/ram.py
Several plot methods in `spacepy.pybats.ram` using syntax that's no longer allowable, passing vmin and vmax to pcolormesh separate from the LogNorm normalizer. From matplotlib 3.3 this issued a warning. From matplotlib 3.5 is raises an error. See also #611.
No explicit testing was added, although I did test that the plot methods now work under matplotlib 3.5.1 by hand. LMK if there are specific tests I should be doing for this (e.g., make a plot w/o showing and just test whether it didn't raise an exception?)
- [N/A] New features and bug fixes should …
=> Fix pcolormesh-based plotting methods in pybats.ram

Doc/source/release_notes.rst, spacepy/datamodel.py, spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
The VarBundle class takes a variable from a CDF file, optionally performs operations on it, and writes it to a new CDF. This PR updates to allow output to a SpaceData object instead of just a CDF.
Most of the nastiness is in the tests, and the diffs look worse than they are--basically the existing tests are refactored into two classes, one of which runs with CDF output, and one which runs with SpaceData output.
=> Support VarBundle output to SpaceData

spacepy/datamodel.py, tests/test_datamodel.py
This PR makes three changes to the `toHDF5` and `fronHDF5` functions in `datamodel`:
1. Does not attempt to compress scalar variables if compression is requested. Previously, the entire toHDF5 function would fail if a single element of the `SpaceData` were scalar.
2. Supports writing Unicode arrays, i.e. Python 3 strings, and also reading them as such.
3. Some light refactoring/cleanup. Mostly this is consolidating lines but I also changed the `import h5py as hdf` to just `import h5py`...it doesn't look like the renaming is a convention anywhere else, and it confused the heck out of me.
The Unicode writing is a bit messy, but it maintains the fallback to "just try it as a 35-element array of bytes" and passes all the tests...this code is somewhat messy anyhow, alas. Another wrinkle is …
=> datamodel to/fromHDF5 improvements (gzip scalars, unicode strings)

spacepy/ctrans/__init__.py, spacepy/time.py
This PR provides two small documentation updates.
The first replaces the erroneous reference to the ITRF (International Terrestrial Reference Frame) with the intended reference to GCRF (Geocentric Celestial Reference Frame). This closes #626.
The second adds GPS to the docstring for `spacepy.time.Ticktock` as it was previously not included in the list of valid input systems. This closes #625.
=> Small updates to ctrans and time docs: fix GCRF and GPS references

Doc/source/release_notes.rst, spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
This PR supports VarBundle operations on SpaceData objects (it's the complement of #624). There's still a bit of CDF-specific sugar where using CDF inputs or outputs, but from the user's perspective a CDF with ISTP metadata and a SpaceData with ISTP metadata will be treated basically the same. Over time I expect to move the ISTP stuff into datamodel and make this all a lot smoother...this is a baby step.
I also pulled out some numpy 1.6 code while I was at it.
=> Support VarBundle input from SpaceData objects

CITATION.cff
This PR adds a `CITATION.cff` file to apply citation metadata on the landing page for the repo, as well as at Zenodo. That is, Zenodo metadata will now be populated from this file rather than using the github profiles of contributors. This file provides control over author names, order, ORCID, etc. and means that manual editing of metadata at Zenodo will no longer be required as a matter of course.
- [N/A] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Add citation metadata for GitHub and Zenodo

.github/workflows/ci.yml
Currently our CI does a daily run at 22:00Z. We also expire the cache of our dependencies at the "beginning of the week", which is at 00:00Z. The first run of the CI after the cache expires takes a long time, as all the dependencies have to be built. It doesn't matter if this first run is the scheduled run or a PR...it is slow, and all subsequent ones for the week are faster. In practice, this means if you open a PR on Monday, the checks take longer to run.
This PR changes the run to 7:37Z. This means the daily run will go (and populate the cache) before most people in Europe or the Americas would be opening a PR. It is off-the-hour to be nice about load balancing, and the 37 is chosen so the minute can clearly not be confused for an hour.
=> Change daily CI run to 7:37Z

Doc/source/install.rst, Doc/source/install_linux.rst, Doc/source/install_mac.rst, Doc/source/release_notes.rst, pyproject.toml, setup.py, spacepy/pycdf/__init__.py, tests/test_base.py
This PR makes some smaller installer changes to make life easier on the Mac, but more importantly it completely rewrites the Mac documentation to reflect the current (onerous) process of getting a working environment on the Mac.
Part of this is changing the build requirement to the minimum version of numpy available, thus closes #638 (which manifested more frequently on Mac.) This also addresses the ``System`` linking, which is related to #583 but I'm not ready to close it based just on this PR.
Other changes made in the course of this (largely coming about from testing install on various ARM platforms):
* pycdf searches more widely on Mac. In addition to looking in /Applications/cdf-*version*, it will look in /Applications/cdf/cdf-*version*. It will also look in both locations relative …
=> Mac installer and documentation updates

Doc/source/pycdf.rst, Doc/source/release_notes.rst, spacepy/pycdf/__init__.py, tests/test_pycdf.py
This PR bundles two small CDF changes from the 0.4.0 project board:
1. Documents the use of `CDF_TMP` and the zlib errors that can result. (Closes #570). This is done with a new "troubleshooting" section of the pycdf docs.
2. Works around a bug in the CDF library when doing epoch conversions near end of day (Closes #285). This was fixed in the latest NASA library, but exists at least as far back as 3.5, so a workaround seems prudent for now. It's a fairly simple fix: Epochs are milliseconds represented as doubles, with millisecond resolution. So the fractional part is always sub-Epoch resolution, and the CDF library always truncates it. The fix is to check for the bug and, if so, truncate Epochs passed in by casting to int. ctypes automatically casts back to a double on the call.
=> Small CDF fixes for 0.4.0

Doc/source/install.rst, spacepy/lib.py
This PR fixes two issues found in testing of 0.4.0rc1.
First, it documents clearing the pip cache. The pip cache is stored at the user level, so it doesn't separate conda and macports builds. This causes problems if mixing them, which is another manifestation of our irbem "circular import" bug.
Second, something in the Windows build chain has changed the name of shared libraries since the 0.3.0 release. Previously libspacepy was `spacepy.dll`. Now, on Python 3.6 it's still `spacepy.dll`; on 3.7+, it's `libspacepy.dll.a`. I don't know what changed; the same version of mingw32 (currently 5.3.0) is used for all current builds, so the difference isn't there. This comes from `compiler.shared_lib_extension` in distutils. The solution is to update `lib.py` to look for the `libspacepy.dll.a` name …
=> Installer-related fixes: Windows dll names; document pip cache clearing

Doc/source/install.rst
This small PR documents using the ``--log`` option to pip, which otherwise eats the output from our installer process (e.g. irbem compile). Closes #622.
=> Document pip logging

.github/workflows/ci.yml, spacepy/irbempy/irbem-lib-20220829-dfb9d26/source/Tsy_and_Sit07_Jul2017.f, spacepy/irbempy/irbem-lib-20220829-dfb9d26/source/onera_desp_lib.f
We keep on trying to keep the Unicode out of the IRBEM source but it keeps creeping back in (#631 this time). This has caused some problems in the past (#190). #214 passes compiler options to make the actual Fortan compiler happy about it.
However, some of the f2py work done before compiling IRBEM is done entirely in numpy Python code, so is unaffected by the fixes in #214. In particular, it will fail if the environment variable ``LANG`` is unset, and probably for certain values of set. (Default in my environment is ``en_US.UTF-8``.
This PR does two things:
- Removes the Unicode characters that were added in the regression of #631.
- Adds a CI check for Unicode in the IRBEM source, so we can catch more easily if this happens in upstream IRBEM again. This was committed, pushed, and tested …
=> Remove Unicode from IRBEM source and check in CI

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, DISTRIBUTE, Doc/source/ci.rst, Doc/source/install_windows.rst, README.md
This PR supports [renaming the default branch](https://github.com/github/renaming/) from ``master`` to ``main``. The actual rename is a configuration change that will be done as soon as this is merged. Closes #476.
GitHub automatically deals with most of this, including repointing PRs. Local clones of a repo and forks in GitHub will need to make small changes. Popups appear on the SpacePy repo in GitHub and on any forks noting the change. The [GitHub documentation](https://github.com/github/renaming/) on this is very good.
Mostly this is documentation changes and one CI change.
This does not remove all references to ``master`` in the codebase, just renames the default branch--some of the rest should be easily eliminated in future work; some may need to stay for consistency with other …
=> Rename default branch to main (Closes #476)

Doc/source/conf.py, spacepy/igrf.py, spacepy/pycdf/__init__.py, spacepy/pycdf/istp.py
This PR is nearly cosmetic. The substantial change is setting a default rST role of `obj` in Sphinx `conf.py`. This enables cross-referencing of Python objects with `` `reference` `` instead of ``:meth:`reference` ``, ``:class:`reference` ``, etc.
But this removes a *lot* of cruft from docstrings and seems worthwhile. I did it on igrf (first that came to hand) and pycdf. It didn't seem worth the time to go through the entire codebase at this point--it can be done piecemeal as people want, or on a documentation scrub. It doesn't *hurt* to keep the old ``:class:`reference` `` syntax.
I also cleaned up a few things to relative reference instead of absolute. In case we rename SpacePy to something else, I guess? (But mostly saving some typing.)
=> Set rST default role to Python object

CHANGELOG, Doc/source/release_notes.rst, spacepy/datamodel.py, tests/test_datamodel.py
Per #448 this pull request updates datamodel to allow for gzip input files. Closes #448 . 
The discussion in #448 called out a few nice to haves that are repeated here 
- allowing for zip as well as gzip 
- this proved problematic based on the interplay of `readJSONheadedASCII` and `readJSONMetadata`
- allowing for mixed lists of input files between regular and gzip
- this was accomplished and a test added. 
I am happy to add another feature request for zip and tgz files as this PR alone is a useful addition to the capability.
=> datamodel.readJSONheadedASCII allows a gzip input file

Doc/source/release_notes.rst, spacepy/datamodel.py, spacepy/pycdf/__init__.py, tests/test_datamodel.py, tests/test_pycdf.py, tests/test_pycdf_istp.py
This PR fixes several issues in datamodel.toCDF:
- Converts to normal keyword arguments
- Fixes handling of the ``backward`` kwarg, which was previously ignored (always set not-backward-compatible mode). This also involved improving set_backward in pycdf to return the current state.
- Fixes the specifying of time types, based on discussion in #652. 0.3.0 basically forced TT2000, since that became the new default type. Now if the TT2000 kwarg is False, EPOCH is used. (Not Epoch16, since it's actually very hard to force "Epoch or Epoch16").
Once #652 is merged, this is going to conflict terribly. I'll fix it at that point. I think it makes sense to merge #652 first though.
=> Enhancements to datamodel.toCDF

.github/workflows/ci.yml, spacepy/coordinates.py, spacepy/datamodel.py, spacepy/igrf.py, spacepy/irbempy/__init__.py, spacepy/plot/carrington.py, spacepy/plot/spectrogram.py, spacepy/plot/utils.py, spacepy/poppy.py, spacepy/pybats/__init__.py, spacepy/pycdf/__init__.py, spacepy/time.py, tests/spacepy_testing.py
This PR fixes all our current Sphinx warnings and adds checks to CI. If the docs fail to build without warnings, the CI will fail.
Most of the Sphinx warnings are fairly straightforward. Some are a matter of providing temporary objects for the autosummary to find, where we have attributes built at run time. I am NOT trying to fix anything other than the Sphinx warnings here--there are some things not in proper numpydoc format, etc.
A note on the CI: this is testing with oldest and newest set of dependencies, not a whole mess. It also is heavily copy/pasted from the unit test runs. This is probably possible to clean up, but primarily wanted to get it working first, and there are subtle differences throughout. Note that there is a new set of pip caches, because the docs install sphinx and …
=> Fix Sphinx warnings; build docs in CI

spacepy/datamodel.py
This PR removes Python 2 specific code from datamodel and performs substantial linting cleanup.
For line length, I was targeting PEP8 option of 100 character lines for code, 72 for docstrings.
Plenty of linting complaints remain, but I wanted to avoid any substantial reorganization of actual functionality (e.g. to reduce indentation levels.) This is just the low-hanging fruit so I can do other datamodel work without having a bunch of linting/style stuff obscuring the diff.
=> datamodel Python 2 removals and linting

Doc/source/index.rst
CI failed building docs because the "spacepy module" object was defined twice: once in index.rst and once in the main spacepy `__init__.py`. (It also failed because the SciPy website was down, but that appears to be transient.) This PR fixes that by changing the index.rst to just declare that spacepy is the current module, but it's not actually defining spacepy.
Other than cleaning up the warning, this means the [module index](https://spacepy.github.io/py-modindex.html) now points to [main module](https://spacepy.github.io/spacepy.html) docs, not [root](https://spacepy.github.io/)...I think that's probably right. We want to distinguish between the API-level docs of the root module and the full documentation of the entire SpacePy package.
=> Make spacepy module in docs refer to main module, not root of docs

.github/workflows/ci.yml
This PR makes two changes to the CI because of changes in GitHub Actions:
- Moves from checkout v2 to checkout v3. This [uses the new version of Node](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) now that GHA has deprecated the older version.
- Replace [set-output](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) with the new `GITHUB_OUTPUT` environment file
- Change [setup-python](https://github.com/actions/setup-python/releases) to v4 (from v2) and cache to v3 (from v2), also for the Node 16 migration.
=> CI updates for github deprecations

spacepy/seapy.py, tests/spacepy_testing.py, tests/test_seapy.py
There are a few ways to provide input to SeaPy that are likely to result in meaningless output. This PR issues a warning on a couple of them: a time series that isn't a simple consistent cadence, and a number of epochs that is large compared to the number of times.
It is possible this is the issue with #665 but there isn't enough information to conclude that.
The PR also removes some Python 2 specific code from spacepy_testing.assertWarns, because that function is used in the tests.
=> Seapy: warn on bad input

Doc/source/datamodel.rst, Doc/source/release_notes.rst, spacepy/datamodel.py, spacepy/plot/spectrogram.py, tests/spacepy_testing.py, tests/test_datamodel.py, tests/test_spectrogram.py
This PR provides methods to plot data in SpaceData assuming they are ISTP-compliant. There are also several helper methods to support this which I intend to continue to flesh out in the future.
This is not going to make a perfect plot of everything yet (for instance, the EPI-Lo data in the example, which I will check on; likely a simpleSpectrogram issue). And we can always add thousands of knobs to tweak. I'd like to try and focus this PR on the core functionality and then we can open up enhancements to build on it.
=> Plot support for SpaceData

spacepy/irbempy/irbempy.py
#377 raises the issue that `spacepy.irbempy.get_Bfield` always returns vector B expressed in Cartesian GEO coordinates. This was not documented and this PR updates the docstring to make clear that GEO coordinates are used.
I'm not setting this PR to close the related issue as we should probably actually handle the case, but that's extra work. This covers the minimal documentation need so hopefully it trips fewer people up. Probably the tag on #377 should change from documentation to enhancement though.
=> Document B vector returned in GEO coordinates by irbempy.get_Bfield

tests/test_seapy.py
`testSeaPlotShowFalse` uses private members of the `AxesSubplot` class to check if it's actually a subplot. This changed in 3.7.0, breaking CI.
This PR changes to a check for the SubplotBase class. The actual class used is constructed at runtime so it's a lot more involved to check for that. [This discussion](https://stackoverflow.com/questions/65082998/test-if-object-is-subplot-in-matplotlib) is relevant.
=> Fix SeaPy test on matplotlib 3.7

spacepy/__init__.py
Our Windows binary wheels ship the mingw32 runtime so that people don't need it installed to run. This involves adding our shipped runtime to the DLL path. Unfortunately this addition was hard-coded, and the runtime _isn't_ there if you build from source on Windows. The result is an error of the form `FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\user\\python\\spacepy\\spacepy\\mingw'`.
This PR makes the DLL path change contingent on the directory actually existing.
I need to muck about a bit to make sure I reproduce the problem and also that this fix works, so draft for now.
=> Check for mingw32 libs before adding to path

Doc/source/release_notes.rst, spacepy/pybats/__init__.py, spacepy/pybats/bats.py, tests/test_pybats.py
This is the revised pull request implementing an optional _sort_unstructured_data_ keyword for pybats.IdlFile.
I established a branch for this feature for this pull request.
The new keyword defaults to _None_ which keeps the old behavior of the IdlFile readers unchanged:
__read_idl_bin()_ implemented sorting of unstructured data and that remains active by default.
__read_idl_ascii()_ did not implement sorting of positions before and the newly added method is not activated by default.
The keyword can be set to _True_ to have data sorted to arrange nearly positions as close as possible to each other, regardless of whether the model output file format is binary or ASCII, or to _False_ to keep the original arrangement of positions as provided in the model output file.
Keeping the original …
=> sort_unstructured_data keyword added to pybats IdlFile method

Doc/source/release_notes.rst, spacepy/pybats/__init__.py, spacepy/pybats/bats.py, tests/test_pybats.py
This PR removes the sorting of unstructured binary data in pybats. It appears this didn't work properly anyhow. Closes #705.
#584 added the ability to leave binary data unsorted (it was sorted by default) and to sort ASCII data (was unsorted by default). As detailed in #705, the sorting was nondeterministic and probably didn't give a desired/useful answer anyway. The qotree code provides a better way of working with adjacent grid points (the goal of the sorting).
So this PR just rips out the sorting altogether. Because the optional sorting was never released, the release notes and such are updated as if that kwarg never happened.
=> pybats.IdlFile: never sort binary inputs

Doc/source/release_notes.rst, spacepy/pybats/__init__.py, spacepy/pybats/bats.py, spacepy/pybats/qotree.py, tests/test_pybats.py
This pull request improves `spacepy.pybats.qotree.QTree` logic and functionality. When building the tree, additional checks are now made to ensure uniform resolution within the block. A new keyword has been added to change the default block size of 8x8 points. This argument can be given to `spacepy.pybats.bats.Bats2d` objects, allowing a broader set of output files to be read in successfully. This change closes issue #696 and improves robustness and functionality of pybats.
Beyond this main change, two other items were addressed:
- Heavy linting was performed on all files touched in this PR. Much of this is long overdue.
- Behavior of plot functions that automatically include inner boundary/planet patches has been changed: if 'rbody' is not found in the object attributes, the patches are …
=> Fix quad tree edge cases and allow non-default block sizes (Closes #696)

.github/workflows/ci.yml, DISTRIBUTE, Doc/source/conf.py, Doc/source/dep_versions.rst, Doc/source/dependencies.rst, Doc/source/install.rst, Doc/source/install_linux.rst, Doc/source/release_notes.rst, MANIFEST.in, developer/scripts/test_all.sh, pyproject.toml, setup.py
This PR reworks the installer into a modern setuptools framework rather than the existing distutils-based setup.py. Some functionality in the distutils namespace is still used; this is provided by setuptools (pypa/setuptools#2806). This also includes, of course, dropping the deprecated numpy distutils. Some other results/implications:
- The required versions of pip, setuptools, and build are now explicitly documented (and testsed)
- Support for Intel and PG compilers is dropped...gfortran only
- A lot of the installer docs are updated since it's all pip, all the way
- Built docs are no longer included in the source distribution (rst source is); it just seems a rare use case and this lets me simplify setup.py
- The installer no longer clears out old files if installing on top of old …
=> Port installer to setuptools (abandon distutils)

tests/test_spectrogram.py
This is a one-liner. One of the test_spectrogram tests was explicitly saving the output and we don't need that...it was basically debugging code that was left in. I tracked it down to #661.
=> test_spectrogram: remove superfluous saving of output on one test

Doc/source/conf.py, Doc/source/release_notes.rst, Doc/source/tests.rst, developer/scripts/build_win.cmd, developer/scripts/win_build_system_setup.cmd, setup.py, tests/spacepy_testing.py
This PR builds on #681. Primarily it supports "editable mode" for installs, which is really just a pathing/symlink trick but compiled code needs special handling (the compiled version of the library gets dumped in the source tree, ick)
One of the big changes here is that instead of compiling irbem and libspacepy as part of the "build" command it's now in the "build_ext" (extension) subcommand. So that means defining some extensions but basically bypassing the normal setuptools extension building code with our own (since it doesn't support Fortran extensions and assumes raw C libraries are only used by Python extensions).
Editable installs basically supplant the "use the build directory" approach, so this removes that handling in unit tests and documentation, and documents that.
Finally …
=> Support editable installs

Doc/source/release_notes.rst, spacepy/datamodel.py, spacepy/toolbox/__init__.py, tests/test_datamodel.py, tests/test_toolbox.py
From discussion in #704, this updates dictree to allow returning (intead of printing) the result. The default remains printing. We could possibly change that (via a deprecation cycle) if we glue on appropriate ipython pretty-print methods. Then ipython would Just Do The Right Thing.
Also extends dictree test coverage and does some refactoring.
=> Update dictree to allow returning not printing the result

CITATION.cff, Doc/source/index.rst, README.md
Our `CITATION.cff` doesn't refer folks to the Niehof et al., 2022 (Spacepy at 12) paper.
This PR changes the file to point to the 2010 conference proceedings and the 2022 update paper.
The change will be visible in two places:
1. When folks click the "cite this repository" link on the github page, and
2. When we tag a new release the metadata gets used by Zenodo, so the citation info will be there.
- [N/A] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Update citation/acknowledgement information

.github/workflows/ci.yml
This PR switches CI to run on Ubuntu 22.04 (jammy) instead of 20.04, so we (hopefully) don't get caught by surprise with changes later. The exception is Python 3.6, which GHA doesn't support on 22.04. For now it stays on 20.04 but 3.6 support will eventually go away anyhow (no rush now).
This also showed up a braino in code that set Fortan options for old scipy. Old scipy needs certain options for new gcc and the code that provided that option wasn't quite right; it showed up in the switch to newer Ubuntu (and newer gcc). This PR fixes that as well.
=> Switch all CI to Ubuntu 22.04

spacepy/toolbox/__init__.py, tests/test_toolbox.py
It appears that inf was removed from the scipy base namespace at some point, so this is now failing to import. Numpy still provides this and the objects are the same in older versions of both libraries.
CI is currently failing because of this, so the change (which is backward compatible) should enable the testing to run on all supported versions.
- [N/A] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Update test_toolbox to fix failing CI: import inf from numpy not scipy

spacepy/plot/__init__.py, spacepy/plot/spectrogram.py, spacepy/pybats/qotree.py, tests/test_all.py, tests/test_plot.py, tests/test_pybats.py, tests/test_spectrogram.py
Fixes a few deprecations from matplotlib 3.5 and 3.6 in pybats and spectrogram. This also improves test coverage, since it tests the pieces of code which were deprecated. Fixes the case where trying to make a pybats grid resolution plot when there was only one resolution.
EDIT: Added a fix for a deprecation in scipy 1.10 and tested levelPlot to catch it.
=> Fix matplotlib 3.5 and 3.6 deprecations

Doc/source/release_notes.rst, spacepy/pybats/__init__.py, spacepy/pybats/ram.py, tests/test_pybats.py
This PR adds two new calculations to the Pybats ImfInput object: clock angle and epsilon (solar wind poynting flux scaled by clock angle). It also adds a new test for **all** calculations in the object class.
Unrelated: the use of Matplotlibs `get_cmap` has been removed from `ram.py`. This was throwing deprecation warnings dating back to MPL 3.7 and is not necessary. Tests still pass.
- [ x] Pull request has descriptive title
- [x ] Pull request gives overview of changes
- [x ] New code has inline comments where necessary
- [ x] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [x ] New features and bug fixes should have unit tests
=> Two new IMF Calculations: clock angle and epsilon

CITATION.cff
The scipy paper has been misformatted in CITATION.cff since it was introduced in 63571812ae81cfa0455a20e4793b711960a5836d, and this is the problem in #736. It bit us again since we don't have that CI implemented. This just fixes the file without implementing the CI, so at least _next_ release the Zenodo might work properly. All this does is remove the location line--it looks like it's superfluous, not like we wanted it to be formatted in properly somewhere else.
Looks like [GitHub is supposed to parse this too](https://citation-file-format.github.io/) so we might have confirmation it's working after the pull.
=> Fix CITATION.cff for Zenodo integraion

spacepy/datamodel.py, tests/test_datamodel.py
Quick fix for the datamodel plot routines when UNITS is blank, i.e. not empty but all spaces. This is the preferred way of showing dimensionless values in ISTP CDF, and most notably it showed up in Kp from MMS MEC. We use LaTeX to render the units, and matplotlib chokes on `$ $`.
This was a regression from 0.5.0 to 0.6.0, where 8c2f42ba0f57d3012051992b3b034b6a90d254ea switched to using LaTeX in the plots.
=> datamodel plot routines: fix all-blank UNITS

.github/workflows/ci.yml, setup.py
CI in #744 failed unrelated to the actual change. setuptools 70 changed the API (pypa/setuptools#4360) so SpacePy build fails. This PR fixes that. It also increases pip's verbosity to help with debugging the issue.
I have confirmed the 0.6.0 binary wheels _install_ fine with 70. #746 documents this until the next release.
=> Fix build on setuptools 70

Doc/source/release_notes.rst, spacepy/__init__.py
Inspired by something in pyspedas, this PR adds an optional kwarg to search the documentation.
At the risk of bikeshedding, I'm curious what the kwarg should be called. I'm using `keyword` because it's the keyword you're searching for, but also considered `search`. In practice probably nobody will use it as a kwarg, just positional.
Since this opens a web browser, it's not very testable in CI.
=> help: take argument to search the documentation

spacepy/toolbox/__init__.py, tests/test_toolbox.py
This pull request slightly improves the test coverage of `spacepy.toolbox`. Removed some unreachable or redundant lines, and added a test for `assemble` with a `sortkey`. See issue #313.
=> Improve Toolbox Test Coverage

spacepy/coordinates.py, spacepy/datamanager.py, spacepy/datamodel.py, spacepy/irbempy/irbempy.py, spacepy/omni.py, spacepy/pycdf/__init__.py, spacepy/seapy.py, tests/test_pycdf.py
Checks for #753 and #755 are failing because the CI is now pulling numpy 2.0. I thought we were deprecation-clean but it looks like numpy 2.0 is changing some things that were not explicitly deprecated before. This PR fixes the test failures.
=> Fix various numpy 2.0 test failures

spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
Made an explicit check, and an assertion for the validchecks on istp. Check that the system produces an error when a non-timetype is compared against a timetype.
Closes #752
=> Explicit checks for type comparisons to CDF_TIME_TT2000 in istp

spacepy/pycdf/istp.py, tests/test_pycdf_istp.py
Added an explicit check for the incorrect fillval being used on an epoch16 type variable, as well as the accompanying unit tests.
Closes #399
=> Handling for incorrect CDF fillval on epoch16 variables

spacepy/empiricals.py
Scipy 1.14 updated the integration.simps() function to integration.simpson(), this is a fix to maintain continuous integration with users who have scipy<1.14
=> Continuous integration fix for users with scipy>=1.14.0

.github/workflows/ci.yml
This fixes a bizarre typo in the CI definition, where for Python 3.9 it was requiring "cython<3.0<3.0". I'm wondering if this is part of why 3.9 is one of the things that always takes forever in the CI. Introduced in #684, 1abb533c87d319dbfbf3aedcc54cf9d5a9f06431
I have no idea why this worked _at all_.
=> ci: fix typo in cython version for python 3.9

tests/spacepy_testing.py, tests/test_pycdf_istp.py
This PR makes two quick changes to the tests:
- The test for #757 was failing on Python 3.6, x86 Mac, numpy 1.12, with different spacing and signs. So this PR loosens the test a bit by making it a regex.
- Any plotting tests that did not save the plot weren't closing the plot object, which eventually issued a warning. This was fixed.
No functional changes.
=> Minor test cleanup

.github/workflows/ci.yml, developer/scripts/test_all.sh
This pull request resolves #765, drastically improving the time it takes to install dependencies for Python 3.9 on the CI. The fix was to simply increase the Pandas version for the "oldest" dependency strategy to >=1.1.3, which is the earliest version of Pandas that supports binary wheels for Python 3.9 ([source](https://pandas.pydata.org/docs/whatsnew/v1.1.3.html)).
=> Bump Pandas minimum version for Python 3.9 in CI and test_all.sh

Doc/source/configuration.rst, Doc/source/release_notes.rst, spacepy/__init__.py, spacepy/ae9ap9.py, spacepy/ctrans/__init__.py, spacepy/datamodel.py, spacepy/empiricals.py, spacepy/igrf.py, spacepy/irbempy/__init__.py, spacepy/omni.py, spacepy/plot/apionly.py, spacepy/pycdf/__init__.py, spacepy/seapy.py, spacepy/time.py, spacepy/toolbox/__init__.py, tests/spacepy_testing.py, tests/test_all.py, tests/test_base.py, tests/test_datamodel.py, tests/test_empiricals.py, tests/test_pycdf.py, tests/test_spectrogram.py, tests/test_time.py, tests/test_toolbox.py
This PR fixes deprecations in numpy 2.0 (and one matplotlib deprecation that was found in the process). Closes #764.
One of these fixes changes the `__array_wrap__` handling so that it's closer to numpy, returning an array scalar (not zero-shape array) for scalar results instead of a Python object. This gets us some bug fixes for free, and tests are added to catch the regressions: closes #12 (SF65 is fixed by this, SF71 was already working in current `main`), closes #528 (looks like it's also working in `main`, but tested now). It then only took a little extra work to fix the incompatibility with pcolormesh; closes #258.
It also makes warnings attributed to spacepy fatal to the test_all process, so the CI will now fail if we have warnings. It's a bit of hack that should be revisited in …
=> Fix numpy 2.0 deprecations

spacepy/pybats/rim.py
Quick fix for pybats.rim.Iono.readascii on numpy 2.1, which doesn't allow the order to be a positional arg anymore.
Also found one stray invalid escape in the rim.Ion.add_cont docstring, so that's fixed.
This is why #775 is failing, and why the CI failed yesterday and today. A deprecation warning would have been nice...
=> numpy 2.1 pybats fix (CI failure)

spacepy/__init__.py, tests/test_base.py
This pull request improves the test coverage of `spacepy/__init__.py`, closes #300. The coverage of this file has been improved since this issue was opened (in #376 and #559), up to 85%. This pull request improves this to 89%.
While writing tests, I noticed a bug in `_write_defaults` that produced erroneous output when `spacepy.rc` has more than one section. I rewrote the latter half of `_write_defaults` with a different approach to fix this. Thinking back on it now, I think a more minimal change was possible, although the new code is significantly shorter than the old code.
Also, `_read_config` contained a smaller bug, where if the initial generic configparser read produced an error, the existing `config` would always be used instead of the defaults. Then, when we try to cast `config` …
=> test_base: Improve test coverage

.github/workflows/ci.yml, Doc/source/conf.py, Doc/source/dep_versions.rst, Doc/source/dependencies.rst, Doc/source/release_notes.rst, README.md, developer/scripts/build_win.cmd, developer/scripts/linux_wheels.sh, developer/scripts/mac_x86_wheels.sh, developer/scripts/test_all.sh, developer/scripts/test_linux_wheels.sh, developer/scripts/test_mac_wheels.sh, developer/scripts/win_build_system_setup.cmd, developer/scripts/win_build_system_teardown.cmd, pyproject.toml, setup.py
The latest version of the GitHub runners, even on Ubuntu 20.04, [removes Python 3.6 support](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md#python). This [broke CI](https://github.com/spacepy/spacepy/actions/runs/10697303743). Since we can no longer test it in CI, this PR removes SpacePy support for Python 3.6 and AstroPy 1.0.
Once 3.7 was our oldest version, the documentation CI was grabbing a version of numpydoc that would install but not work on 3.7. So this PR also establishes a minimum version of numpydoc (0.8.0).
Several of our actions were using old versions that had a deprecated node.js, so this PR also updates those runners (as long as we're messing with CI).
=> Remove Python 3.6 support

spacepy/sandbox/radbelt.rst
#783 moved data_assimilation and related to sandbox. It also removed the relevant docs from quickstart.rst. I intended, but neglected, to put those docs in sandbox as well. This PR fixes that omission.
=> Add radbelt, data_assimilation docs to sandbox

tests/test_base.py
#775 hardcoded the "UNRELEASED" version number in a test, making tests fail when run against a released version of SpacePy. This PR fixes that test.
=> test_base: fix test for config file writing with released SpacePy

spacepy/pybats/__init__.py, tests/integration_all.py, tests/integration_pybats.py, tests/test_pybats.py
Closes #810 
Change a few integers that default to numpy int32 to int64 to prevent overflow errors when opening large (>2Gb) files with IdlFile objects in Pybats. 
- [ x] Pull request has descriptive title
- [x ] Pull request gives overview of changes
- [ x] New code has inline comments where necessary
- [n/a ] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [ n/a] Added an entry to release notes if fixing a significant bug or providing a new feature
- [ n/a] New features and bug fixes should have unit tests
- [ x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)
=> Changing some integers to 64 bit so numpy >=2.0 can handle large files.
